### ISSUE TITLE
redis:subscribe接口导致程序崩溃bug

### ISSUE THREAD

**Issue by nicelogic** [acl-dev/acl#101]
//redis.subscribe多运行几次，必现
redis_pubsub::subop
{
const char** argv = (const char**) dbuf_->dbuf_alloc(argc * sizeof(char*));
...略略略...
run{！！！may free argv}
check_channel(argv[0])  //argv已被free导致程序崩溃
}
最开始run里面不会清楚内存池，会导致内存泄露
后续加了，这个波及到了

**Comment by zhengshuxin** [comment]
能否写一个简单的示例，把问题具体说一下？
