### ISSUE TITLE
arm_v5t4_le-gcc交叉编译lib_acl的问题。

### ISSUE THREAD

**Issue by kiddriver** [acl-dev/acl#104]
main函数使用 -acl的方式链接动态库 libacl.so。在libtool: link的时候出现 
libacl.so: undefined reference to '__tync_lock_test_and_set_8'
libacl.so: undefined reference to '__sync_fetch_and_add_8'
libacl.so: undefined reference to '__sync_fetch_and_fetch_8'
 但是使用-acl的方式链接静态库却没有出现上述错误。动态库有问题，静态库没有问题。

目前还没找到解决办法。麻烦帮忙看一下大概有什么解决方法。

**Comment by kiddriver** [comment]
也试过arm-linux-gcc，也是一样的问题

**Comment by zhengshuxin** [comment]
这几个API是内核支持的原子操作，不知道您所用的 LINUX 内核是否有这些 API

**Comment by kiddriver** [comment]
__sync_fetch_and_add_4是有的，但是__sync_fetch_and_add_8没有找到。不过链接静态库并没有报错，链接时就出错了。

**Comment by zhengshuxin** [comment]
静态链接时如果可执行程序不调用是不会报错的，动态库要求必须要有。你用的哪个 Linux ?

**Comment by zhengshuxin** [comment]
如果是内核确实没有，则你可以通过修改 lib_acl/src/std/acl_atomic.c 文件，注掉 “# defineHAS_ATOMIC"，从而使 acl 内部自动使用线程锁。

**Comment by kiddriver** [comment]
好，我试一下。

**Comment by kiddriver** [comment]
这样可以，多谢帮忙。 我再想想这个问题，链接过程报的错和实际板子跑的linux有关系？代码我在ubuntu上编的。

**Comment by zhengshuxin** [comment]
ok
