### ISSUE TITLE
building on windows with visual studio 2017 to generate dll get a link error

### ISSUE THREAD

**Issue by runrunwang** [acl-dev/acl#108]
使用windows 最新的visual studio 2017 compile lib_acl project 生成dll
会产生如下的link error
error LNK2019: unresolved external symbol GetAdaptersInfo referenced in function acl_get_ifaddrs

简单看是缺少一个library文件如下所示
#pragma comment(lib,"iphlpapi.lib")

**Comment by zhengshuxin** [comment]
目前 acl 提供了 vc2017 工程，可以使用 2017 进行编译了。至于 iphlpapi.lib 库，你需要从微软官方获取，我的 2017 应该是有该文件 的。
