### ISSUE TITLE
publish return 0, but there is peer listening and peer seems do receive the message

### ISSUE THREAD

**Issue by colinzuo** [acl-dev/acl#109]
Hi,

There is a redis cluster, and I use redis client redis-cli to subscribe to certain channel.

Then I use acl redis publish command to publish to the channel, but the result is unexpected,
it returns 1 for one time, then 0 for the next time, then continue in this 1 0 1 0 ... pattern.

And actually redis-cli displays all messages, so I would expect all return 1, why some not?

Any idea?

Thanks

**Comment by colinzuo** [comment]
more info, the problem occurs when call some other command such as redis_key.exist first, then call redis_pubsub.publish. Sample code as below:
acl::redis_client_cluster cluster;
cluster.set(addr.c_str(), 100, conn_timeout, rw_timeout);

for (int i = 0; i < 4; i++) {
        char key_info[256];
		
        if (true) {
            snprintf(key_info, 256, "any.key");

            acl::redis_key cmd_key;
            cmd_key.set_cluster(&cluster, 100);

            if (!cmd_key.exists(key_info)) {
                // do something
            }
        }

       if (ret) {
			acl::redis_pubsub redis;

			redis.set_cluster(&cluster, 100);

                        acl::string channel = "any.channel";
                        std::string sendString = "hello";
                        ret = redis.publish(channel.c_str(), sendString.c_str(), sendString.length());
                        printf("ret %d\n", ret);
		}
}

The output will be:
ret 0
ret 1
ret 0
ret 1

If not call redis_key.exists, or use different cluster instance for publish, the output will be all 1.

**Comment by zhengshuxin** [comment]
You can use the sample test again:
static void test(acl::redis_client_cluster& cluster)
{
        for (int i = 0; i < 4; i++) {
                char key_info[256];

                snprintf(key_info, 256, "any.key");

                acl::redis_key cmd_key(&cluster);

                if (!cmd_key.exists(key_info)) {
                        // do something
                }

                acl::redis_pubsub redis;

                redis.set_cluster(&cluster, 100);

                acl::string channel = "any.channel";
                std::string sendString = "hello";
                int ret = redis.publish(channel.c_str(), sendString.c_str(),
                        sendString.length());
                printf("channel=%s, ret %d\n", channel.c_str(), ret);
        }
}

**Comment by zhengshuxin** [comment]
You can test again with the below code:

```c++
static void test(acl::redis_client_cluster& cluster)
{
        for (int i = 0; i < 4; i++) {
                char key_info[256];
                snprintf(key_info, 256, "any.key");
                acl::redis_key cmd_key(&cluster);
                if (!cmd_key.exists(key_info)) {
                        // do something
                }

                acl::redis_pubsub redis(&cluster);
                acl::string channel = "any.channel";
                std::string sendString = "hello";
                int ret = redis.publish(channel.c_str(), sendString.c_str(),
                        sendString.length());
                printf("channel=%s, ret %d\n", channel.c_str(), ret);
        }
}
```

**Comment by colinzuo** [comment]
(BTW, you didn't mean I need to upgrade before test, right? current version is acl-3.3.0)

Sorry for the late response. Just tried and found something more.

First, the output is not the same for different input, for some data, the publish always return success,
for some it doesn't.

Second, there are some output on console about connect_manager, not sure if related.

The actual test code I use is as below:

```
static void test(acl::redis_client_cluster& cluster)
{
	int username_start = 136100000;
        int deviceid_start = 138100000;

	int user_cnt = 5;
        int devices_per_user = 2;
	int seq = 0;

	for (int user_idx = 3; user_idx < user_cnt; user_idx++) {
		for (int device_idx = 0; device_idx < devices_per_user; device_idx++) {
			for (int i = 0; i < 4; i++) {
				int username = username_start + user_idx*100;
				int deviceid = deviceid_start + user_idx*100 + device_idx;

				char key_info[256];
				snprintf(key_info, 256, "dolphin.reg.user.%d.device.%d", username, deviceid);

				bool result_ok = true;

				{	
					acl::redis_key cmd_key(&cluster);
					if (!cmd_key.exists(key_info)) {
						printf("key %s: not exists\n", key_info);
						result_ok = false;
					} else {
						printf("key %s: exists\n", key_info);
					}
				}

				acl::string target_ws_server_id;

				if (result_ok)
				{
					acl::redis_hash cmd_hash(&cluster);

					if (!cmd_hash.hget(key_info, "ws-server-id", target_ws_server_id)) {
						printf("key %s: get target server id failed\n", key_info);
						result_ok = false;
					} else {
						printf("key %s: target server id %s\n", key_info, target_ws_server_id.c_str());
					}
				}
				
				if (result_ok)
				{
					char reg_key_publish_message[256];
                	                snprintf(reg_key_publish_message, 256, "dolphin.wss.id.%s.message", target_ws_server_id.c_str());

					char hello_content[256];
					snprintf(hello_content, 256, "hi seq %d", seq++);

					acl::redis_pubsub redis(&cluster);
					int ret = redis.publish(reg_key_publish_message, hello_content, strlen(hello_content));
					printf("channel=%s, content=%s, ret %d\n", reg_key_publish_message, hello_content, ret);
				}
			}
		}
	}
}

```
The console output:

connect_manager.cpp(184), set: Add one service, addr: 172.26.0.44:7000, count: 100
connect_manager.cpp(239), get: no connect pool for addr 172.26.0.41:7000
connect_manager.cpp(184), set: Add one service, addr: 172.26.0.41:7000, count: 0
key dolphin.reg.user.136100300.device.138100300: exists
key dolphin.reg.user.136100300.device.138100300: target server id 68864086-140c-4e61-828b-159d73406495
channel=dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message, content=hi seq 0, ret 0
key dolphin.reg.user.136100300.device.138100300: exists
key dolphin.reg.user.136100300.device.138100300: target server id 68864086-140c-4e61-828b-159d73406495
channel=dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message, content=hi seq 1, ret 1
key dolphin.reg.user.136100300.device.138100300: exists
key dolphin.reg.user.136100300.device.138100300: target server id 68864086-140c-4e61-828b-159d73406495
channel=dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message, content=hi seq 2, ret 0
key dolphin.reg.user.136100300.device.138100300: exists
key dolphin.reg.user.136100300.device.138100300: target server id 68864086-140c-4e61-828b-159d73406495
channel=dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message, content=hi seq 3, ret 1
key dolphin.reg.user.136100300.device.138100301: exists
key dolphin.reg.user.136100300.device.138100301: target server id 68864086-140c-4e61-828b-159d73406495
channel=dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message, content=hi seq 4, ret 1
key dolphin.reg.user.136100300.device.138100301: exists
key dolphin.reg.user.136100300.device.138100301: target server id 68864086-140c-4e61-828b-159d73406495
channel=dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message, content=hi seq 5, ret 0
key dolphin.reg.user.136100300.device.138100301: exists
key dolphin.reg.user.136100300.device.138100301: target server id 68864086-140c-4e61-828b-159d73406495
channel=dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message, content=hi seq 6, ret 1
key dolphin.reg.user.136100300.device.138100301: exists
key dolphin.reg.user.136100300.device.138100301: target server id 68864086-140c-4e61-828b-159d73406495
channel=dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message, content=hi seq 7, ret 0

I started one redis client to psubscribe the channel, it's output is:

1) "pmessage"
2) "dolphin.wss.id.*.message"
3) "dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message"
4) "hi seq 0"
1) "pmessage"
2) "dolphin.wss.id.*.message"
3) "dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message"
4) "hi seq 1"
1) "pmessage"
2) "dolphin.wss.id.*.message"
3) "dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message"
4) "hi seq 2"
1) "pmessage"
2) "dolphin.wss.id.*.message"
3) "dolphin.wss.id.68864086-140c-4e61-828b-159d73406495.message"
4) "hi seq 3"

**Comment by zhengshuxin** [comment]
I've just fixed one important bug in redis_command::run which affected the redis_pubsub class.
--zsx
