### ISSUE TITLE
File in repository triggered virus scan

### ISSUE THREAD

**Issue by undisputed-seraphim** [acl-dev/acl#113]
Hi,

I'd like to raise your attention to a particular text file in your repository, which upon cloning, triggered my antivirus.
It appears to be a zip file encoded in base64 (attachment of that sample email).
If that file is decoded back into a zip file and then uncompressed, it appears to contain a trojan.

[This is the file.](https://github.com/acl-dev/acl/blob/master/lib_acl_cpp/samples/mime/mime/4.eml)

I hope this file can be scrubbed from the git history so that unsuspecting users will not accidentally unleash a trojan upon themselves.

**Comment by zhengshuxin** [comment]
This is only one mime file for testing acl's mime library. I've removed it now.
Thanks.
