### ISSUE TITLE
master服务器下的master_ctld服务进程频繁重启

### ISSUE THREAD

**Issue by skyviewo** [acl-dev/acl#118]
make install 后，利用acl\dist\master下安装脚本，会自动将几个acl\app\master\tools几个工具考到libexec\目录下，运行后发现master_ctld服务被启动后会自动退出，被master进程反复重启，经过分析发现，启动服务时参数带入了‘-v’选项，而app\master\tools\master_ctld\main\main.c中check_version()函数在判断-v时会调用exit()。

**Comment by zhengshuxin** [comment]
需要最新的 acl_master 服务模块，-v 已经在其中去掉了

**Comment by skyviewo** [comment]
更新了代码，在启动master进程时加入 “-V”选项，还会导致master_ctld反复重启，是因为master加上"-V"选项会导致service_args()生成服务进程参数时，加上了'-v'。

**Comment by zhengshuxin** [comment]
恩，看来传参方面需要定义一个规则才成，以免产生冲突。
