### ISSUE TITLE
[redis][renamenx]  check please

### ISSUE THREAD

**Issue by jungjongheun** [acl-dev/acl#119]
os : windows 10
version : 3.4.1

In Redis, 'rename' command returns simple_string and 'renamenx' command returns integer value. But In ACL Library, both of 'rename' and 'renamenx' function return the value of bool type.
is this correct? I think that 'renamenx' function should return interger value.

**Comment by zhengshuxin** [comment]
Yes, there is one problem in redis_key::renamenx about the returned value's type. I've just fixed it.
Thanks.
-zsx
