### ISSUE TITLE
ACL3.4中redis效率问题

### ISSUE THREAD

**Issue by swgzj** [acl-dev/acl#124]
我通过压力测试，发现ACL3.4的redis效率很低，我改成ACL3.3版本就解决了问题，你们是否遇到过类似的问题，难道在3.4中需要有什么开关配置或者使用上有区别？

**Comment by zhengshuxin** [comment]
能否给写一个简单示例？

**Comment by swgzj** [comment]
[src.zip](https://github.com/acl-dev/acl/files/2391572/src.zip)
我的代码

**Comment by zhengshuxin** [comment]
你的代码太多了吧，能否把代码精简一下？另外，我用 acl/lib_fiber/samples/redis 下的例子压测，性能并没有降低。
