### ISSUE TITLE
acl 的日志库能否实现按照日期创建日志文件

### ISSUE THREAD

**Issue by iahob** [acl-dev/acl#128]
日志文件每天按照日期自动创建日志文件，这样可以很方便管理，从example中我知道通过open可以创建一个日志文件

**Comment by zhengshuxin** [comment]
当前acl库本身的日志模块还不支持分割文件功能，但你可以通过两种方式达到这一目的：
1、可设置日志输出定向，与 syslog-ng 配合使用，利用 syslog-ng 的强大功能；
2、可以通过 acl 日志的 hook 方式，使第三方的日志库与 acl 库配合使用。
具体方法可参考：http://zsxxsz.iteye.com/blog/1893115
