### ISSUE TITLE
ACL线程池acl_pthread_pool_t工作线程有阻塞和超时机制吗

### ISSUE THREAD

**Issue by PrinceJane** [acl-dev/acl#129]
线程池中的工作线程是否存在运行超时提前被强制结束的情形：
1.acl_pthread_pool_set_schedule_warn，如果设置了该值，线程调度时间超过此值仅仅是生成警告日志吗？会不会如题所述强制结束工作线程；
2.acl_pthread_pool_set_schedule_wait，该函数是否也跟如题所述问题有关？

**Comment by zhengshuxin** [comment]
acl_pthread_pool_set_schedule_warn 设置的值目前确实是仅起报警作用，以便于应用来优化业务，将来可以考虑将过期的任务丢弃。
