### ISSUE TITLE
websocket upload_server 例子的问题

### ISSUE THREAD

**Issue by laochen** [acl-dev/acl#130]
lib_acl_cpp/samples/websocket/upload_server 目录下的 http_servlet.cpp 文件
第289行  		case acl::FRAME_BINARY:  
后面应该增加一行
                         	case acl::FRAME_CONTINUATION:
用来处理分片的情况，fin为false，op_code为acl::FRAME_CONTINUATION 的数据也是实际的传输数据

**Comment by laochen** [comment]
这样好像还是有问题，存下的数据不对

**Comment by laochen** [comment]
存下数据异常的原因是mask处理的一个bug
lib_acl_cpp/src/http/websocket.cpp 
第379行  buf[i] ^= mask[i % 4]; 
应该改为 buf[i] ^= mask[(payload_nread_ + i) % 4];

**Comment by zhengshuxin** [comment]
是的，当循环调用此方法时，掩码的处理方式有误，非常感谢!

**Comment by zhengshuxin** [comment]
是的，当循环调用此方法时，掩码的处理方式有误，非常感谢，问题已修复。

**Comment by laochen** [comment]
谢谢老郑

**Comment by hellokandy** [comment]
ACL库，除了可以websocket实现文件的上传。还有别的解决方案吗？我想在C++客户端上传到服务端，有好的方案建议吗？
