### ISSUE TITLE
redis_client_pool支持选择redis database吗

### ISSUE THREAD

**Issue by chenguang9239** [acl-dev/acl#132]
JedisPool的构造函数中有一个database参数用来指定要选择的database，默认为0号。请问acl的redis_client_pool支持选择redis database吗？

**Comment by chenguang9239** [comment]
redis_connection.hpp中有select函数；
如果从池中获取到连接 auto conn = (acl::redis_client*) pool.peek();
然后选择数据库：
acl::redis operation(conn);
operation.select(0);
但是这样的话，每次获取连接之后都要执行一次选择database的操作，有没有统一设置的办法？

**Comment by zhengshuxin** [comment]
目前还没有提供统一的设置方法

**Comment by chenguang9239** [comment]
> 目前还没有提供统一的设置方法

好的；另外是否支持pipeline？

**Comment by zhengshuxin** [comment]
集群模式下无法支持pipeline，而acl redis 当初出现时因需要同时集群模式及单点模式，所以选择不支持pipeline，将来也许会暴露底层通信接口，让上层应用自己去实现这点；acl redis 当初的设计初衷是可以象使用 stl 一样简单，业务不必关系协议及通信的细节。

**Comment by zhengshuxin** [comment]
现在的开发版已经支持在非集群模式下建立连接时自动选择db了，参考：redis_client 及 redis_client_pool 中的方法：set_db.

**Comment by zhengshuxin** [comment]
现在在集群或单点模式下已经可以支持 pipeline 模式了，性能得到几倍提升。
