### ISSUE TITLE
http_server示例中，void http_rpc::rpc_run()是线程安全函数吗？

### ISSUE THREAD

**Issue by hellokandy** [acl-dev/acl#139]
示例代码如下：
// 调用 service_.rpc_fork 后，由 RPC 框架在子线程中调用本函数
// 来处理本地其它模块发来的请求信息
void http_rpc::rpc_run()
{
	// 打开阻塞流对象
	socket_stream stream;

	// 必须用 get_vstream() 获得的 ACL_VSTREAM 流对象做参数
	// 来打开 stream 对象，因为在 acl_cpp 和 acl 中的阻塞流
	// 和非阻塞流最终都是基于 ACL_VSTREAM，而 ACL_VSTREAM 流
	// 内部维护着了一个读/写缓冲区，所以在长连接的数据处理中，
	// 必须每次将 ACL_VSTREAM 做为内部流的缓冲流来对待
	ACL_VSTREAM* vstream = client_->get_vstream();
	ACL_VSTREAM_SET_RWTIMO(vstream, 10);
	(void) stream.open(vstream);

	rpc_req_add();

	// 开始处理该 HTTP 请求
	handle_conn(&stream);

	rpc_req_del();

	// 将 ACL_VSTREAM 与阻塞流对象解绑定，这样才能保证当释放阻塞流对象时
	// 不会关闭与请求者的连接，因为该连接本身是属于非阻塞流对象的，需要采
	// 用异步流关闭方式进行关闭
	stream.unbind();
}

在handle_conn(&stream);这里想根据action来处理客户端的请求，但是不确定该函数是否线程安全？

**Comment by zhengshuxin** [comment]
是线程安全的。该示例为非阻塞框架和线程池结合的方式，异步获得一个连接并创建异常连接对象（aio_socket_stream），然后通过 rpc 机制将该异步对象交给线程池中的一个线程进行处理（即通过 rpc_manager 里面绑定的线程池中的一个线程去处理）。
