### ISSUE TITLE
C++客户端，除了可以websocket实现文件的上传。ACL还有别的解决方案吗？

### ISSUE THREAD

**Issue by hellokandy** [acl-dev/acl#141]
使用C++开发客户端，需要上传文件到服务端，ACL除了websocket的方案，还有别的解决方案吗？盼复~

**Comment by zhengshuxin** [comment]
acl 的 HTTP 协议模块提供了 http multipart/form 的文件上传方案，可以参考例子：https://github.com/acl-dev/acl/tree/master/app/wizard_demo/httpd_upload

**Comment by hellokandy** [comment]
感谢回复------------------ 原始邮件 ------------------发件人: 郑树新  <notifications@github.com>发送时间: 2019年3月18日 18:38收件人: acl-dev/acl <acl@noreply.github.com>抄送: zhouwei <kandy230@163.com>, Author <author@noreply.github.com>主题: 回复：[acl-dev/acl] C++客户端，除了可以websocket实现文件的上传。ACL还有别的解决方案吗？ (#141)acl 的 HTTP 协议模块提供了 http multipart/form 的文件上传方案，可以参考例子：https://github.com/acl-dev/acl/tree/master/app/wizard_demo/httpd_upload

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/acl-dev/acl","title":"acl-dev/acl","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/acl-dev/acl"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zhengshuxin in #141: acl 的 HTTP 协议模块提供了 http multipart/form 的文件上传方案，可以参考例子：https://github.com/acl-dev/acl/tree/master/app/wizard_demo/httpd_upload\r\n"}],"action":{"name":"View Issue","url":"https://github.com/acl-dev/acl/issues/141#issuecomment-473857135"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/acl-dev/acl/issues/141#issuecomment-473857135",
"url": "https://github.com/acl-dev/acl/issues/141#issuecomment-473857135",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hellokandy** [comment]
> 
> 
> acl 的 HTTP 协议模块提供了 http multipart/form 的文件上传方案，可以参考例子：https://github.com/acl-dev/acl/tree/master/app/wizard_demo/httpd_upload

这个demo在运行的时候，会报错！提示缺少zlib1.dll，我找了整个项目，只是在 zlib_stream.cpp 文件中找到zlib.dll 是由static void __zlib_dll_load(void)负责加载的，但是没找到zlib1.dll是由谁生成的！

自己编译了一个zlib的dll工程，然后把zlib.dll改名为zlib1.dll后，放到httpd_upload.exe同目录下，运行程序，发现程序不报错了！可以正常收到web端发送过来的文件！是否zlib1.dll就是zlib库直接编译且没有经过再次封装的呢？

最后，担心zlib的版本不一致的问题，还是希望可以提供生成zlib1.dll的vs工程，以便消除心中疑虑。3Q~
