### ISSUE TITLE
google的protocol buffers经过SerializeToString后（二进制数据），怎么通过acl库成功存储到redis里面？

### ISSUE THREAD

**Issue by chee1986** [acl-dev/acl#142]
google的protocol buffers经过SerializeToString后（二进制数据），怎么通过acl库成功存储到redis里面？

**Comment by zhengshuxin** [comment]
acl 的 redis 模块中的 redis_string 就可以存放二进制到 Redis 中。

**Comment by chee1986** [comment]
嗯，已成功，需要填一下size，不然会被截断，3Q
