### ISSUE TITLE
Question: Chinese characters in source code

### ISSUE THREAD

**Issue by lefig** [acl-dev/acl#143]
This is a great project and thank you to all contributors.

I have a query and would appreciate your thoughts - how do I display within VS 2017 code comments that are encoded in source files? I have tried everything.

Thanks

**Comment by zhengshuxin** [comment]
I'm sorry that the comments was written in Chinese with GBK charset. You can translate the comments to English from Chinese by the Google translate(http://translate.google.com). Maybe I'll rewrite the comments in English in future.
--zsx

**Comment by lefig** [comment]
Thank you
