### ISSUE TITLE
How to set multiple nodes in the acl::redis_client_cluster

### ISSUE THREAD

**Issue by pravinmote88** [acl-dev/acl#146]
Hi,

I have a redis cluster with 3 masters and I am trying to use this redis client for the cluster.

I need to have acl redis interface to talk to the redis cluster. Below is something simple I have tried.

    acl::string addr("10.0.2.15:6381"), addr1("10.0.2.15:6382"), addr2("10.0.2.15:6383");

    acl::redis_client_cluster cluster;
    
    cluster.set(addr, conn_timeout, rw_timeout);
    cluster.set(addr1, conn_timeout, rw_timeout);
    cluster.set(addr2, conn_timeout, rw_timeout);

    acl::redis redis_instance;
    redis_instance.set_cluster(&cluster, 100);

    acl::string key = "aclKey", val= "aclvalue";
    if(redis_instance.set(key, val) == false)
    {
        printf("Key not set \n");
    }
    else 
    {
        printf("key is set\n");
    }

Is there any other better way to set multiple cluster nodes?
I need to load lua scripts to this cluster and perform some complex task.

**Comment by zhengshuxin** [comment]
You can just set only one master's addr by calling cluster.set(addr, max_connections_for_each_node, conn_timeout, rw_timeout),  the other masters'  addrs will be  found automatically in running. 
If you do need to set all the addrs of all masters, you can call cluster.init(NULL, "10.0.2.15:6381; 10.0.2.15:6382; 10.0.2.15:6383", max_connections_for_each_node, conn_timeout, rw_timeout).
--zsx

**Comment by pravinmote88** [comment]
Thanks zhengshuxin.

**Comment by pravinmote88** [comment]
But for loading lua script, we need to load the script on each node.
Is there any way to load the script on all nodes of the cluster?
