### ISSUE TITLE
Question: How is the Redis client able to run so fast?

### ISSUE THREAD

**Issue by lefig** [acl-dev/acl#147]
Hi there,

I have been doing some recent bench marking against another redis client. The performance difference is remarkable and ACL must be up there with zeromq when it comes to speed. Thank you for that. I was wondering how this is achieved?

Thanks again

**Comment by zhengshuxin** [comment]
In acl redis module, the connection pool, memory pool, IO buffer were used, especially the memory pool named dbuf increased the performance of acl redis.

**Comment by zhengshuxin** [comment]
The pipeline mode has been completed in acl redis module recently, so the performance has been improved with more times:)
