### ISSUE TITLE
redis cluster client core in acl

### ISSUE THREAD

**Issue by jaczuo** [acl-dev/acl#15]
We used acl as clients to visit our redis cluster but in the performance test, we got segment fault and the stack trace is as follwoing.
#0  0x0000000000602c7b in acl::redis_client_cluster::set_slot (this=0x1e2cf10, slot=14780,

```
addr=0x20 <Address 0x20 out of bounds>) at src/redis/redis_client_cluster.cpp:88
```
#1  0x0000000000608b86 in acl::redis_command::run (this=0x7f81315ec500, cluster=0x1e2cf10, nchild=0)

```
at src/redis/redis_command.cpp:448
```
#2  0x000000000060932b in acl::redis_command::get_number (this=<value optimized out>, success=0x0)

```
at src/redis/redis_command.cpp:603
```

It seems that the argument addr passed to set_slot is invalid. Our program runs in multi-thread environment, not sure if this is related.

Thanks.

**Comment by jaczuo** [comment]
version is 3.1.2

**Comment by zhengshuxin** [comment]
This bug existed in version3.1.2, and had been fixed in dev version. You can use the current dev version in your project, I'll post a new release version a few days later.
Thanks.
