### ISSUE TITLE
针对redis stream的阻塞问题

### ISSUE THREAD

**Issue by arkonchen** [acl-dev/acl#151]
现在在使用redis stream的时候，xreadgroup函数设置block为0时是非阻塞模式。
但是在使用redis-cli时，block为0是为阻塞模式，请问后续会修改acl中设置block为0时为阻塞模式吗，或者有其他方法设置阻塞模式吗

**Comment by zhengshuxin** [comment]
谢谢提醒，该问题已修复，当 block 为 0 时采用阻塞模式，-1 时为非阻塞模式，> 0 则等待超时。
---zsx

**Comment by arkonchen** [comment]
> 谢谢提醒，该问题已修复，当 block 为 0 时采用阻塞模式，-1 时为非阻塞模式，> 0 则等待超时。
> ---zsx

您好，看了您修改的代码后，与我昨天自行修改的一致。但是我测过之后，发觉xreadgroup只是阻塞一段时间，还是会返回false，并不是一直处于阻塞，直到收到新的message，请您可否再看下。

**Comment by zhengshuxin** [comment]
那是受了连接池的读超时限制影响，你可以在添加 redis 服务节点时，指定读时时间为 0，有两个方法与之有关：acl::connect_manager::init() 或 acl::connect_manager::set() 中的 rw_timeout 值设为 0，内部缺省值为 30 秒，所以即使设置了阻塞方法，然后会因这个超时设置而导致在 30 秒后返回。

**Comment by arkonchen** [comment]
> 那是受了连接池的读超时限制影响，你可以在添加 redis 服务节点时，指定读时时间为 0，有两个方法与之有关：acl::connect_manager::init() 或 acl::connect_manager::set() 中的 rw_timeout 值设为 0，内部缺省值为 30 秒，所以即使设置了阻塞方法，然后会因这个超时设置而导致在 30 秒后返回。

好的，多谢
