### ISSUE TITLE
Issue with executing a script with multiple keys

### ISSUE THREAD

**Issue by pravinmote88** [acl-dev/acl#152]
Hi,

I have written a small script which has two keys. These keys have a tag to have them in a single node of cluster.
The script increments the values of those two keys -

_local id = '12345'
local key1 = 'abc.{user1000}. followers'
local key2 = 'abc.{user1000}. following'
redis.call('INCR', key1)
redis.call('HINCRBY', key2, id, 1)_

This script executed from redis-cli.
With acl-redis client, this script loads but when executed gives error as -
lua script attempted to access non-local key in a cluster node.

Please let me know if there are rules for tagging the key.
Also please let me know if there is any example of lua script execution using acl-redis client.

**Comment by zhengshuxin** [comment]
In redis cluster mode, multi-keys can't be used in acl redis, because the redis node of cluster can only handle keys belonged to it by crc16 hash. So you can't use multi-keys in redis cluster.  There is no example for acl redis script commands now, maybe  I'll write some in later.

**Comment by pravinmote88** [comment]
As per redis cluster documentation, to have multi-key operation on redis cluster all the concerned keys are required to be in the same node. This can be ensured using same hash tag in all the concerned keys.
Is this operation not supported with this client yet?
For adding an example of script load and execute, I will be glad to contribute.

**Comment by zhengshuxin** [comment]
Yes, the acl redis client can not seperate and collect the same hash tag for multi-keys from the given keys, so, only one key can be used in redis cluster. There're many changes in acl redis to support multi-keys in redis cluster. Redis's script is a mapping for lua script, I'll add one example after I've learned Lua language.

**Comment by pravinmote88** [comment]
Ok. Thank You.
