### ISSUE TITLE
编译lib_acl_cpp静态库出错

### ISSUE THREAD

**Issue by ConstantineW** [acl-dev/acl#153]
编译lib_acl_cpp静态库的时候出现了错误，如下：
src/stdlib/charset_conv.cpp:277:20: 错误：passing argument 2 to restrict-qualified parameter aliases with argument 4 [-Werror=restrict]
   __iconv(m_iconv, &pNil, &zero, &pNil, &zero);
请问大家有没有遇见过这种问题，该怎么解决呢，谢谢。

**Comment by zhengshuxin** [comment]
因为每个平台上的 iconv 库的 API 声明有些差别，你可以根据相应的 API 参数来做转换，比如：
__iconv(m_iconv, (const char**) &pNil, &zero, &pNil, &zero);

**Comment by ConstantineW** [comment]
编译的选项中含有-Werror选项，会将警告当作错误处理，由于restrict不允许同一函数形参中两个指针指向同一地址（passing argument 2 to restrict-qualified parameter aliases with argument 4 [-Werror=restrict]），而在__iconv中&pNil, &zero都是指向同一地址，所以会出现编译警告，进而无法编译成功。有两种解决办法。
1，去除g++中的-Werror选项；
2，找到iconv的定义，我的在/usr/include中，去除restrict。（似乎restrict只起到了优化代码的作用，去除后不影响程序运行，不知是否是这样）

**Comment by zhengshuxin** [comment]
看样子是同一个参数在__iconv 中被用了两次导致的，可以这样尝试一下：
char* pNil = NULL, *pNil2 = NULL;
size_t zero = 0, zero2 = 0; 
__iconv(m_iconv, &pNil, &zero, &pNil2, &zero2);

**Comment by ConstantineW** [comment]
嗯，也是可以的，谢谢，哈哈
