### ISSUE TITLE
first new project build issue

### ISSUE THREAD

**Issue by munna1116** [acl-dev/acl#154]
Hello, 
I am using ubuntu OS 
I have compiled the library files by going to the path of the libraries as mentioned in the descriptions.
first lib_acl, lib_proptocol, lib_acl_cpp. Everything was fine.
But if I create a New project in a seperate folder, I am unable to build make file of the project.
I have even followed the below path setting:

CFLAGS = -c -g -W -O3 -Wall -Werror -Wshadow \
-Wno-long-long -Wpointer-arith -D_REENTRANT \
-D_POSIX_PTHREAD_SEMANTICS -DLINUX2 \
-I ./home/user/workspace/acl/lib_acl_cpp/include
BASE_PATH=./home/user/workspace/acl
LDFLAGS = -L$(BASE_PATH)/lib_acl_cpp/lib -l_acl_cpp \
	-L$(BASE_PATH)/lib_protocol/lib -l_protocol \
	-L$(BASE_PATH)/lib_acl/lib -l_acl \
	-lpthread
test: main.o
	g++ -o main.o $(LDFLAGS)
main.o: main.cpp
	g++ $(CFLAGS) main.cpp -o main.o

It is throwing **seperator missing** some times and **spaces are present instead of tab**.
if cleared those issue then it throws **"acl_cpp/lib_acl.h"**  not found .  ** No rule to make target  'g++'  needed by 'filename.o'. stop

Thanks in advance

**Comment by zhengshuxin** [comment]
I wrote the Makefile as follow and built ok.

```
CC     = g++
CFLAGS = -c -g -W \
-Wall \
-Wcast-qual \
-Wcast-align \
-Wno-long-long \
-Wpointer-arith \
-Werror \
-Wshadow \
-O3 \
-D_REENTRANT \
-D_POSIX_PTHREAD_SEMANTICS \
-D_USE_FAST_MACRO

ACL_PATH = /home/zsx/work/github/acl
CFLAGS += -I$(ACL_PATH)/lib_acl/include \
          -I$(ACL_PATH)/lib_protocol/include \
          -I$(ACL_PATH)/lib_acl_cpp/include
LDFLAGS = -L$(ACL_PATH)/lib_acl_cpp/lib -lacl_cpp \
          -L$(ACL_PATH)/lib_protocol/lib -lprotocol \
          -L$(ACL_PATH)/lib_acl/lib -lacl \
          -lpthread -lz -ldl

COMPILE = $(CC) $(CFLAGS)
LINK    = $(CC) $(OBJ) $(LDFLAGS)

###########################################################

OBJ_PATH = .

#Project's objs
SRC = $(wildcard *.cpp)
OBJ = $(patsubst %.cpp, $(OBJ_PATH)/%.o, $(notdir $(SRC)))

$(OBJ_PATH)/%.o: %.cpp
        $(COMPILE) $< -o $@

.PHONY = all clean
PROG = server
all: $(OBJ)
        $(LINK) -o $(PROG)
clean:
        rm -f $(PROG)
        rm -f $(OBJ)
```
And the source code show below:

```c++
#include "acl_cpp/lib_acl.hpp"

int main(void)
{
        acl::acl_cpp_init();
        const char* addr = "127.0.0.1:8081";
        acl::server_socket ss;
        if (ss.open(addr) == false) {
                printf("listen on %s error %s\r\n", addr, acl::last_serror());
                return 1;
        }
        printf("listen %s ok\r\n", addr);
        while (true) {
                acl::socket_stream* conn = ss.accept();
                if (conn == NULL) {
                        printf("accept error %s\r\n", acl::last_serror());
                        break;
                }
                printf("accept one ok\r\n");
                delete conn;
        }
        return 0;
}
```

You can write one sample as it and try again. 
--zsx
