### ISSUE TITLE
Secure communication with Redis server using SSL

### ISSUE THREAD

**Issue by dev-konrad** [acl-dev/acl#155]
Hi,

I've been using your library for a while in a project connecting to clustered Redis - it works nice - many thanks for this code.
However, at this point, we need to introduce secure communication, about which I haven't seen anything in examples or tutorial.
Is there a way to do it?

Thanks,
Konrad

**Comment by zhengshuxin** [comment]
Do you mean supporting SSL communication with Redis server ? If so, I think I can add it in the future. There're SSL module in acl library including polarssl_conf/polarssl_io(need the polarssl) which can used for supporting SSL communication.
---zsx

**Comment by dev-konrad** [comment]
Yes, exactly that.
Yeah, I saw polarssl too, when browsing the code. Do you think it's a lot of work to implement it?
For now I think I'll go for stunnel solution as I don't have much time to wait.

Thanks,
Konrad

**Comment by zhengshuxin** [comment]
It's easy for me to add it to redis, because the polarssl wrapper in acl is powerful and easy to use. I'll add it to acl redis.
--zsx

**Comment by zhengshuxin** [comment]
SSL communication has been supported in acl redis client. You can see the sample in https://github.com/acl-dev/acl/tree/master/lib_acl_cpp/samples/redis/redis_ssl. And the specified polarssl used by acl lib can be found in https://github.com/acl-dev/third_party.
After you've compiled the sample, you can run "./redis -s 127.0.0.1:6379 -c -S ./libpolarssl.so -a set" where the flag "-S" should be set to the ssl libpath.
--zsx

**Comment by dev-konrad** [comment]
WOW, that was fast! Thanks so much.
I wasn't replying to you, but I'm already working on trying this out in my setup.
I should have a result this week - will let you know how it works.

Thanks,
Konrad
