### ISSUE TITLE
error LNK2001: 无法解析的外部符号 acl_optarg

### ISSUE THREAD

**Issue by jialebifashi** [acl-dev/acl#159]
lib_acl.lib
lib_acl_cpp.lib
lib_protocol.lib
releasedll x64 三个库已经设置好
自己的release x64环境   main生成时总是报
error LNK2001: 无法解析的外部符号 acl_optarg
acl_optarg明明在 lib_acl.lib 中！找不到什么原因

静态库 release编译好后使用是OK的，动态DLL就是不行

**Comment by zhengshuxin** [comment]
在使用动态库时需要定义预定义：ACL_DLL, ACL_CPP_DLL

**Comment by jialebifashi** [comment]
> 在使用动态库时需要定义预定义：ACL_DLL, ACL_CPP_DLL

感谢！  问题解决！

还有两个疑问望解答：
1.subscribe后getmessage没有超时设定，只能一直等下去吗？
2.publish发布消息后所有的订阅者都能拿到，能否设置只有一人拿到，例如消费者模型那种，因为我没有看到ACL中有消费者队列模式，请问是否支持？

**Comment by zhengshuxin** [comment]
1、getmessage 协议本身是没有超时机制的，所以只能一直等下去；
2、这个不取决于 acl 本身，而是要遵守 redis 官方协议标准。

**Comment by jialebifashi** [comment]
> 1、getmessage 协议本身是没有超时机制的，所以只能一直等下去；
> 2、这个不取决于 acl 本身，而是要遵守 redis 官方协议标准。

非常感谢！
