### ISSUE TITLE
acl的memcached库支持缓存图片吗？

### ISSUE THREAD

**Issue by 2263486zx** [acl-dev/acl#160]
你好，我们的项目正在使用您编写的库，现在我们有一个需求是：
客户端向servlet服务端发送http的post请求，请求的报文是multipart/form-data格式，体中添加了图片附件。在servlet端，我是用getHttpMime获取，并且按照sample中的方法，读取到mime中每个节点，将每个节点内附件的内容保存至memcache中。
我现在遇到两个问题：
1. 获取到的node节点应该通过什么方式保存节点内的文件附件？
2. acl的memcache库是否支持存储图片？
我的描述不知道是否清楚，如果有什么地方描述不到位请告诉我，谢谢。

**Comment by zhengshuxin** [comment]
1. 请先参照例子：https://github.com/acl-dev/acl/blob/master/app/wizard_demo/httpd_upload/http_servlet.cpp 中的 doParse 方法，取得 mime node 节点，然后参考 http_mime_node 的基类 mime_node，选择一个 save 方法即可获得文件附件；
1. acl memcache 是一个客户端库，支持将二进制数据存 入 memcached 服务器中。

**Comment by 2263486zx** [comment]
@zhengshuxin 非常感谢你的回复，我现在使用这个例子中的代码成功获得了Mime_node，但是总是在最后调用save的时候失败，提示m_emailFile empty!，我确信我测试时是上传了文件的，我想问下这个函数第二个参数const char* src的作用是什么，看注释写的是邮件内容的起始地址，默认是Null，因为我在例子中看到都没有填，所以我也没有填（因为我不知道要填什么），但是我在调试时发现，如果src是null，那么最终代码会走到bool mime_node::save(pipe_manager& out) const这个函数里，判断m_emailFile是空并且报错返回。

**Comment by 2263486zx** [comment]
@zhengshuxin 感谢你的耐心解答，我尝试了你提供的例子的方法，不知道哪里出了问题，每次在save的地方都会失败，显示m_emailFile是空的，我很纳闷这个函数中src（邮件内容起始地址）的参数如何填写，我看你的例子中都是使用默认值也就是NULL，我也这样填，但是每次都失败。
但是我参考你的例子直接使用req.getInputStream()的方式读取到二进制数据也达到了我的目的，总之非常感谢你！
如果可以的话能否解答我上面提到的关于save的函数问题，再次感谢！

**Comment by zhengshuxin** [comment]
在文件开始上传前，创建的 mime_ 对象必须通过 mime_->set_saved_path(path) 指定上传的数据包的文件路径，该文件里存的内容为从 req.getInputStream() 里读的数据。边从输入流里读数据边写入该 path，同时需要边调用 mime_->update() 进行 MIME 解析。这样最后你便可以通过 mime_->save() 将 mime 各个区域的数据进行转存。

**Comment by 2263486zx** [comment]
OK，谢谢耐心讲解，我搞懂了。
