### ISSUE TITLE
使用aclhttp内存问题

### ISSUE THREAD

**Issue by hviden** [acl-dev/acl#161]
你好,最近一直在用acl库,发现调用多次http请求进程内存会一直增长,我看源码http_hdr_res.c中第70行:
        acl_pthread_once(&once_control, thread_cache_init);
	pool = (ACL_ARRAY*) acl_pthread_getspecific(cache_key);
	if (pool == NULL) {
		pool = acl_array_create(100);
		acl_pthread_setspecific(cache_key, pool);
		if ((unsigned long) acl_pthread_self() == acl_main_thread_self()) {
			main_cache = pool;
			atexit(main_cache_free);
		}
	}

min_cache只有在进程结束时才去释放,我使用vld查看内存状况,有很多acl_array_grow

--------- Block 305 at 0x01207ED8: 456 bytes ----------
  Leak Hash: 0xAE8FBC74, Count: 1, Total 456 bytes
  Call Stack (TID 11544):
    0x77481F00 (File and line number not available): ntdll.dll!RtlAllocateHeap
    f:\dd\vctools\crt_bld\self_x86\crt\src\malloc.c (89): acl_http.exe!malloc + 0x3B bytes
    v:\developer\acl-master\lib_acl\src\stdlib\memory\acl_default_malloc.c (229): acl_http.exe!acl_default_malloc + 0x6 bytes
    v:\developer\acl-master\lib_acl\src\stdlib\memory\acl_malloc_glue.c (146): acl_http.exe!acl_malloc_glue + 0xD bytes
    v:\developer\acl-master\lib_acl\src\stdlib\common\acl_array.c (137): acl_http.exe!acl_array_grow + 0xF bytes
    v:\developer\acl-master\lib_acl\src\stdlib\common\acl_array.c (190): acl_http.exe!acl_array_dbuf_create + 0x9 bytes
    v:\developer\acl-master\lib_acl\src\stdlib\common\acl_array.c (162): acl_http.exe!acl_array_create + 0xA bytes
    v:\developer\acl-master\lib_protocol\src\http\http_hdr_res.c (73): acl_http.exe!http_hdr_res_new + 0x8 bytes
    v:\developer\acl-master\lib_acl_cpp\src\http\http_request.cpp (364): acl_http.exe!acl::http_request::request + 0xB bytes
    d:\project\acl_http\acl_http\acl_http.cpp (207): acl_http.exe!acl_http_request + 0x13 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (347): acl_http.exe!reqttt + 0x58 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (366): acl_http.exe!test + 0x9 bytes
    0x76E00419 (File and line number not available): KERNEL32.DLL!BaseThreadInitThunk + 0x19 bytes
    0x774A662D (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xED bytes
    0x774A65FD (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xBD bytes
 

而且持续增长,我已经把请求放到线程去执行了,这个要怎么处理呢?谢谢!

**Comment by hviden** [comment]
另外附加一份vld内存数据,我看都是在获取请求头的时候调用http_hdr_res_new.


---------- Block 508 at 0x01207D08: 52 bytes ----------
  Leak Hash: 0x4B757827, Count: 1, Total 52 bytes
  Call Stack (TID 3384):
    0x77481F00 (File and line number not available): ntdll.dll!RtlAllocateHeap
    f:\dd\vctools\crt_bld\self_x86\crt\src\malloc.c (89): acl_http.exe!malloc + 0x3B bytes
    v:\developer\acl-master\lib_acl\src\private\private_fifo.c (93): acl_http.exe!private_fifo_new + 0x7 bytes
    v:\developer\acl-master\lib_protocol\src\http\http_hdr_res.c (74): acl_http.exe!http_hdr_res_new + 0xC bytes
    v:\developer\acl-master\lib_acl_cpp\src\http\http_request.cpp (364): acl_http.exe!acl::http_request::request + 0xB bytes
    d:\project\acl_http\acl_http\acl_http.cpp (207): acl_http.exe!acl_http_request + 0x13 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (347): acl_http.exe!reqttt + 0x58 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (366): acl_http.exe!test + 0x9 bytes
    0x76E00419 (File and line number not available): KERNEL32.DLL!BaseThreadInitThunk + 0x19 bytes
    0x774A662D (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xED bytes
    0x774A65FD (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xBD bytes
  Data:
    58 7D 20 01    58 7D 20 01    01 00 00 00    0D F0 AD BA     X}..X}.. ........
    0D F0 AD BA    0D F0 AD BA    0D F0 AD BA    39 83 3B 00     ........ ....9.;.
    69 83 3B 00    92 83 3B 00    C7 83 3B 00    0D F0 AD BA     i.;...;. ..;.....
    0D F0 AD BA                                                  ........ ........


---------- Block 510 at 0x01207D58: 12 bytes ----------
  Leak Hash: 0xF396BC96, Count: 1, Total 12 bytes
  Call Stack (TID 3384):
    0x77481F00 (File and line number not available): ntdll.dll!RtlAllocateHeap
    f:\dd\vctools\crt_bld\self_x86\crt\src\malloc.c (89): acl_http.exe!malloc + 0x3B bytes
    v:\developer\acl-master\lib_acl\src\private\private_fifo.c (121): acl_http.exe!private_fifo_push + 0x7 bytes
    v:\developer\acl-master\lib_acl\src\thread\acl_pthread.c (443): acl_http.exe!acl_pthread_setspecific + 0xE bytes
    v:\developer\acl-master\lib_protocol\src\http\http_hdr_res.c (74): acl_http.exe!http_hdr_res_new + 0xC bytes
    v:\developer\acl-master\lib_acl_cpp\src\http\http_request.cpp (364): acl_http.exe!acl::http_request::request + 0xB bytes
    d:\project\acl_http\acl_http\acl_http.cpp (207): acl_http.exe!acl_http_request + 0x13 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (347): acl_http.exe!reqttt + 0x58 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (366): acl_http.exe!test + 0x9 bytes
    0x76E00419 (File and line number not available): KERNEL32.DLL!BaseThreadInitThunk + 0x19 bytes
    0x774A662D (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xED bytes
    0x774A65FD (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xBD bytes
  Data:
    58 4B 20 01    00 00 00 00    00 00 00 00                    XK...... ........


---------- Block 371 at 0x01207D88: 56 bytes ----------
  Leak Hash: 0x44846DB7, Count: 1, Total 56 bytes
  Call Stack (TID 12260):
    0x77481F00 (File and line number not available): ntdll.dll!RtlAllocateHeap
    f:\dd\vctools\crt_bld\self_x86\crt\src\malloc.c (89): acl_http.exe!malloc + 0x3B bytes
    v:\developer\acl-master\lib_acl\src\stdlib\memory\acl_default_malloc.c (229): acl_http.exe!acl_default_malloc + 0x6 bytes
    v:\developer\acl-master\lib_acl\src\stdlib\memory\acl_default_malloc.c (252): acl_http.exe!acl_default_calloc
    v:\developer\acl-master\lib_acl\src\stdlib\memory\acl_malloc_glue.c (169): acl_http.exe!acl_calloc_glue + 0x10 bytes
    v:\developer\acl-master\lib_acl\src\stdlib\common\acl_array.c (174): acl_http.exe!acl_array_dbuf_create + 0x11 bytes
    v:\developer\acl-master\lib_acl\src\stdlib\common\acl_array.c (162): acl_http.exe!acl_array_create + 0xA bytes
    v:\developer\acl-master\lib_protocol\src\http\http_hdr_res.c (73): acl_http.exe!http_hdr_res_new + 0x8 bytes
    v:\developer\acl-master\lib_acl_cpp\src\http\http_request.cpp (364): acl_http.exe!acl::http_request::request + 0xB bytes
    d:\project\acl_http\acl_http\acl_http.cpp (207): acl_http.exe!acl_http_request + 0x13 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (347): acl_http.exe!reqttt + 0x58 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (366): acl_http.exe!test + 0x9 bytes
    0x76E00419 (File and line number not available): KERNEL32.DLL!BaseThreadInitThunk + 0x19 bytes
    0x774A662D (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xED bytes
    0x774A65FD (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xBD bytes
  Data:
    AD DE 00 00    30 00 00 00    00 00 00 00    70 00 00 00     ....0... ....p...
    00 00 00 00    88 82 20 01    46 C7 3B 00    4F C7 3B 00     ........ F.;.O.;.
    60 C3 3B 00    7D C3 3B 00    B4 C3 3B 00    F2 C3 3B 00     `.;.}.;. ..;...;.
    1E C4 3B 00    63 C4 3B 00                                   ..;.c.;. ........


---------- Block 373 at 0x01207DD8: 52 bytes ----------
  Leak Hash: 0x4B757827, Count: 1, Total 52 bytes
  Call Stack (TID 12260):
    0x77481F00 (File and line number not available): ntdll.dll!RtlAllocateHeap
    f:\dd\vctools\crt_bld\self_x86\crt\src\malloc.c (89): acl_http.exe!malloc + 0x3B bytes
    v:\developer\acl-master\lib_acl\src\private\private_fifo.c (93): acl_http.exe!private_fifo_new + 0x7 bytes
    v:\developer\acl-master\lib_protocol\src\http\http_hdr_res.c (74): acl_http.exe!http_hdr_res_new + 0xC bytes
    v:\developer\acl-master\lib_acl_cpp\src\http\http_request.cpp (364): acl_http.exe!acl::http_request::request + 0xB bytes
    d:\project\acl_http\acl_http\acl_http.cpp (207): acl_http.exe!acl_http_request + 0x13 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (347): acl_http.exe!reqttt + 0x58 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (366): acl_http.exe!test + 0x9 bytes
    0x76E00419 (File and line number not available): KERNEL32.DLL!BaseThreadInitThunk + 0x19 bytes
    0x774A662D (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xED bytes
    0x774A65FD (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xBD bytes
  Data:
    50 7E 20 01    50 7E 20 01    01 00 00 00    0D F0 AD BA     P~..P~.. ........
    0D F0 AD BA    0D F0 AD BA    0D F0 AD BA    39 83 3B 00     ........ ....9.;.
    69 83 3B 00    92 83 3B 00    C7 83 3B 00    0D F0 AD BA     i.;...;. ..;.....
    0D F0 AD BA                                                  ........ ........


---------- Block 374 at 0x01207E28: 16 bytes ----------
  Leak Hash: 0x5D577E66, Count: 1, Total 16 bytes
  Call Stack (TID 12260):
    0x77481F00 (File and line number not available): ntdll.dll!RtlAllocateHeap
    f:\dd\vctools\crt_bld\self_x86\crt\src\malloc.c (89): acl_http.exe!malloc + 0x3B bytes
    v:\developer\acl-master\lib_acl\src\stdlib\memory\acl_default_malloc.c (229): acl_http.exe!acl_default_malloc + 0x6 bytes
    v:\developer\acl-master\lib_acl\src\thread\acl_pthread.c (443): acl_http.exe!acl_pthread_setspecific
    v:\developer\acl-master\lib_protocol\src\http\http_hdr_res.c (74): acl_http.exe!http_hdr_res_new + 0xC bytes
    v:\developer\acl-master\lib_acl_cpp\src\http\http_request.cpp (364): acl_http.exe!acl::http_request::request + 0xB bytes
    d:\project\acl_http\acl_http\acl_http.cpp (207): acl_http.exe!acl_http_request + 0x13 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (347): acl_http.exe!reqttt + 0x58 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (366): acl_http.exe!test + 0x9 bytes
    0x76E00419 (File and line number not available): KERNEL32.DLL!BaseThreadInitThunk + 0x19 bytes
    0x774A662D (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xED bytes
    0x774A65FD (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xBD bytes
  Data:
    AD DE 00 00    08 00 00 00    90 20 41 00    90 7D 20 01     ........ ..A..}..


---------- Block 375 at 0x01207E50: 12 bytes ----------
  Leak Hash: 0xF396BC96, Count: 1, Total 12 bytes
  Call Stack (TID 12260):
    0x77481F00 (File and line number not available): ntdll.dll!RtlAllocateHeap
    f:\dd\vctools\crt_bld\self_x86\crt\src\malloc.c (89): acl_http.exe!malloc + 0x3B bytes
    v:\developer\acl-master\lib_acl\src\private\private_fifo.c (121): acl_http.exe!private_fifo_push + 0x7 bytes
    v:\developer\acl-master\lib_acl\src\thread\acl_pthread.c (443): acl_http.exe!acl_pthread_setspecific + 0xE bytes
    v:\developer\acl-master\lib_protocol\src\http\http_hdr_res.c (74): acl_http.exe!http_hdr_res_new + 0xC bytes
    v:\developer\acl-master\lib_acl_cpp\src\http\http_request.cpp (364): acl_http.exe!acl::http_request::request + 0xB bytes
    d:\project\acl_http\acl_http\acl_http.cpp (207): acl_http.exe!acl_http_request + 0x13 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (347): acl_http.exe!reqttt + 0x58 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (366): acl_http.exe!test + 0x9 bytes
    0x76E00419 (File and line number not available): KERNEL32.DLL!BaseThreadInitThunk + 0x19 bytes
    0x774A662D (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xED bytes
    0x774A65FD (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xBD bytes
  Data:
    30 7E 20 01    00 00 00 00    00 00 00 00                    0~...... ........


---------- Block 305 at 0x01207ED8: 456 bytes ----------
  Leak Hash: 0xAE8FBC74, Count: 1, Total 456 bytes
  Call Stack (TID 11544):
    0x77481F00 (File and line number not available): ntdll.dll!RtlAllocateHeap
    f:\dd\vctools\crt_bld\self_x86\crt\src\malloc.c (89): acl_http.exe!malloc + 0x3B bytes
    v:\developer\acl-master\lib_acl\src\stdlib\memory\acl_default_malloc.c (229): acl_http.exe!acl_default_malloc + 0x6 bytes
    v:\developer\acl-master\lib_acl\src\stdlib\memory\acl_malloc_glue.c (146): acl_http.exe!acl_malloc_glue + 0xD bytes
    v:\developer\acl-master\lib_acl\src\stdlib\common\acl_array.c (137): acl_http.exe!acl_array_grow + 0xF bytes
    v:\developer\acl-master\lib_acl\src\stdlib\common\acl_array.c (190): acl_http.exe!acl_array_dbuf_create + 0x9 bytes
    v:\developer\acl-master\lib_acl\src\stdlib\common\acl_array.c (162): acl_http.exe!acl_array_create + 0xA bytes
    v:\developer\acl-master\lib_protocol\src\http\http_hdr_res.c (73): acl_http.exe!http_hdr_res_new + 0x8 bytes
    v:\developer\acl-master\lib_acl_cpp\src\http\http_request.cpp (364): acl_http.exe!acl::http_request::request + 0xB bytes
    d:\project\acl_http\acl_http\acl_http.cpp (207): acl_http.exe!acl_http_request + 0x13 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (347): acl_http.exe!reqttt + 0x58 bytes
    d:\project\acl_http\acl_http\acl_http.cpp (366): acl_http.exe!test + 0x9 bytes
    0x76E00419 (File and line number not available): KERNEL32.DLL!BaseThreadInitThunk + 0x19 bytes
    0x774A662D (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xED bytes
    0x774A65FD (File and line number not available): ntdll.dll!RtlGetAppContainerNamedObjectPath + 0xBD bytes
  Data:
    AD DE 00 00    C0 01 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........
    00 00 00 00    00 00 00 00    00 00 00 00    00 00 00 00     ........ ........

**Comment by hviden** [comment]
今天调试发现,线程退出时并没有调用到thread_cache_free函数.
现在临时解决办法就是不使用hdr_cache,否则hdr_cache不会自动释放,造成内存泄漏.

是我使用方法有问题吗?

**Comment by hviden** [comment]
原因终于知道了!
必须使用acl库中的创建线程函数acl_pthread_create!!!
否则内部默认开启hdr_cache会导致线程退出时没调用到acl设置的释放函数,造成内存泄漏.

解决方法:
要么使用acl_pthread_create来创建线程,要么主动调用http_hdr_cache(0);设置不使用hdr缓存.

还是推荐使用acl的acl_pthread_create去创建线程.

**Comment by zhengshuxin** [comment]
> 原因终于知道了!
> 必须使用acl库中的创建线程函数acl_pthread_create!!!
> 否则内部默认开启hdr_cache会导致线程退出时没调用到acl设置的释放函数,造成内存泄漏.
> 
> 解决方法:
> 要么使用acl_pthread_create来创建线程,要么主动调用http_hdr_cache(0);设置不使用hdr缓存.
> 
> 还是推荐使用acl的acl_pthread_create去创建线程.

赞！
