### ISSUE TITLE
connection is_open

### ISSUE THREAD

**Issue by mahdisn76** [acl-dev/acl#165]
hi,
I was wondering whether I can check the connection was successful or not? It is needed in scenarios like redis server is not open.

**Comment by zhengshuxin** [comment]
In the redis cluster mode, you can use acl::redis_client_cluster as the connections manager for each acl redis commands. The connections managed by redis_client_cluster will re-connect the redis-server when one connection lost, so the connecting process is handled automaticlly internal. Maybe I can give some methods to show the connecting status.
---zsx
