### ISSUE TITLE
'HttpServletRequest' class shall automatically parse json when content type is 'application/json'

### ISSUE THREAD

**Issue by bladewhistle** [acl-dev/acl#166]
The HttpServletRequest class will automatically parse json when body_parse_ is true and content type is 'text/json', but for most cases the json content-type is 'application/json', so suggest to automatically parse json for this case, thanks.

**Comment by zhengshuxin** [comment]
Content type as 'application/json'  can be parsed automatically now in the current development version in HttpServletRequest.
---zsx

**Comment by bladewhistle** [comment]
Got it thx.
