### ISSUE TITLE
Client setname command on Redis cluster

### ISSUE THREAD

**Issue by dev-konrad** [acl-dev/acl#168]
Hi,

I'm trying to set client name on connections I open to Redis cluster.
This was successful using an implemented command `client_setname`, although the name is set only on one connection you use for calling the command.
Therefore on any connections opened further on, name is not set.

The library opens a lot of connections during its running - I checked that using `connect_monitor::on_connected`. I even thought I could use this callback to set client name in it, but not sure it's possible or a good idea.

Any suggestions how can that be implemented?

edit:
Challenge I see with that is that (I assume) ACL is not keeping connections open, but creates them once needed (is that right?). So another option might be to set them to live forever and only set name on them in beginning.

edit2:
I debugged it a bit and it looks like the best place to set client name is `redis_client::open` after `conn_.open()`. Would that make sense? Additional question is: why this connection here is open so many times, in other words why isn't it persistent? Sorry, so many questions :)

Thanks,
Konrad

**Comment by zhengshuxin** [comment]
There's no method to set client name for one connection in cluster mode now, maybe I'll enable it later.  The connection pool was used in acl::redis_client_cluster which inheriting from acl::connect_manager and the connect_manager manages many connection pool for some redis-server nodes. One connection will be keeped for a while after first created and will be released after a configurable idle timeout, so in a busy running status, many connections will be reused many times.

-- zsx

**Comment by dev-konrad** [comment]
Ok, thanks for an answer.
The way I would implement it is: I would set the string with name in redis_client and then set it on any new connection being open.
That's how it's done in lettuce for example:
https://lettuce.io/lettuce-4/release/api/com/lambdaworks/redis/RedisURI.html#setClientName-java.lang.String-
