### ISSUE TITLE
acl::redis_client是线程安全的吗？

### ISSUE THREAD

**Issue by StanleyWm** [acl-dev/acl#169]
acl::redis_client建立的conn，可以在多线程中使用吗？Demo中只给出了acl::redis_client_cluster是线程安全的，所以想确认一下。

**Comment by zhengshuxin** [comment]
acl::redis_client 不是线程安全的，同一个对象不能同时用在多个线程中，而 acl::redis_client_cluster 同一个类对象是可以用在多个线程中。

**Comment by StanleyWm** [comment]
> acl::redis_client 不是线程安全的，同一个对象不能同时用在多个线程中，而 acl::redis_client_cluster 同一个类对象是可以用在多个线程中。

谢谢
