### ISSUE TITLE
lib_acl_cpp的socket示例中，打开端口失败

### ISSUE THREAD

**Issue by hellokandy** [acl-dev/acl#170]
路径 ：acl\lib_acl_cpp\samples\socket[s1|s2|server]
问题描述：打开地址的时候，一直都是失败的！
`acl::server_socket server;
	acl::string addr = "127.0.0.1:9001";

	if (argc >= 2)
		addr = argv[1];

	if (server.open(addr) == false)//这里会打开失败
	{
		printf("open %s error\r\n", addr.c_str());
		return 1;
	}
	else
		printf("open %s ok\r\n", addr.c_str());`

**Comment by zhengshuxin** [comment]
因为在Windows平台下 SOCKET 需要初始化，而这几个例子最初是针对 UNIX 平台编写的。现在已经修改可以在Windows下运行了，方法是在进程开始处通过添加方法 acl::acl_cpp_init() 来初始化 SOCKET。
--zsx

**Comment by hellokandy** [comment]
感谢回复！我会尽快测试一下！------------------ 原始邮件 ------------------发件人: 郑树新  <notifications@github.com>发送时间: 2019年8月23日 21:35收件人: acl-dev/acl <acl@noreply.github.com>抄送: zhouwei <kandy230@163.com>, Author <author@noreply.github.com>主题: 回复：[acl-dev/acl] lib_acl_cpp的socket示例中，打开端口失败 (#170)因为在Windows平台下 SOCKET 需要初始化，而这几个例子最初是针对 UNIX 平台编写的。现在已经修改可以在Windows下运行了，方法是在进程开始处通过添加方法 acl::acl_cpp_init() 来初始化 SOCKET。
--zsx

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/acl-dev/acl/issues/170?email_source=notifications\u0026email_token=ACHXEIAIEB6AZ2Y2QSOEXPLQF7RQZA5CNFSM4IO5BU22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5AHGJA#issuecomment-524317476",
"url": "https://github.com/acl-dev/acl/issues/170?email_source=notifications\u0026email_token=ACHXEIAIEB6AZ2Y2QSOEXPLQF7RQZA5CNFSM4IO5BU22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5AHGJA#issuecomment-524317476",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
