### ISSUE TITLE
使用acl::thread_pool运行后总出现.\src\thread\acl_pthread_pool.c(269), worker_run: schedule: 4157 >= 100提示

### ISSUE THREAD

**Issue by jialebifashi** [acl-dev/acl#173]
主要使用(主线程)如下：
acl::thread_pool ThreadsPool;
ThreadsPool.set_limit(ThreadCounts);  //ThreadCounts为确定值
ThreadsPool.start();
......其他代码.....
ThreadsPool.execute(new Fredthread(m_TheMessage, &m_MyRedis, m_pWordsMatcher, m_pBow, &m_locker));

运行一段时间后总会出现如下提示
.\src\thread\acl_pthread_pool.c(269), worker_run: schedule: 4157 >= 100
其中 x >= 100   x每次都是不同值
请问这个提示是什么意思，是否意味着某个地方设置的有问题？我的线程现在是越跑越慢，耗时越来越长，不知是否跟此处有关，望解答谢谢！

**Comment by zhengshuxin** [comment]
当一个执行任务加入线程池执行队列到该任务被一个线程接管，如果时间差大于指定的值（默认值是100ms），则内部就出现警告，acl 线程池是动态调整的，当达到最大线程数时，则后续的任务就得要排队。解决方法有两个，一个是应用层提升业务处理速度，另一个是增加线程池中最大线程数。
目前看，应该是你的逻辑耗时较大，导致线程池中的线程都被占用，后续的任务只能是排队了。
--- zsx

**Comment by jialebifashi** [comment]
原来如此
还遇到一个问题，当给子线程定一个耗时很久的任务时，运行一段时间，我直接在主线程调用ThreadsPool.stop();但是子线程仍然正常运行，并不停止，请问这是哪里设置不对吗？

**Comment by zhengshuxin** [comment]
acl 线程库调用停止方法时，并不是强制停止，而是需要等待所有线程都处于空闲状态时才会正常停止。
