### ISSUE TITLE
redis集群有节点挂掉后，执行命令耗时比较多的问题

### ISSUE THREAD

**Issue by StanleyWm** [acl-dev/acl#175]
您好，我的使用场景是这样的：
初始化集群连接池
```
acl::redis_client_cluster* m_pRedisClientConn = new acl::redis_client_cluster;
for (auto iter = setHosts.cbegin(); iter != setHosts.cend(); ++iter)
{
    m_pRedisClientConn->set((*iter).c_str(), 0, 10, 10);
}
```

每次需要执行操作时，生成新的cmd
```
acl::redis_string cmd_str(m_pRedisClientConn);
```

当集群中一个slave节点挂掉后，有新命令需要处理时，会有可能出现该命令耗时10秒（我怀疑是我设置的连接超时时间）的情况，是否是因为每次生成新的cmd的时候，都会去尝试连接redis？

我应该怎么做才能避免这个耗时的出现？

**Comment by zhengshuxin** [comment]
可以通过 redis_client_cluster 类中的 set_redirect_max() 和 set_redirect_sleep() 方法设置节点down掉时休眠等待的次数和每次休眠的时间（毫秒），具体可参考头文件说明。
