### ISSUE TITLE
How to reject upload request correctly

### ISSUE THREAD

**Issue by bladewhistle** [acl-dev/acl#176]
Hi, 

I'm using acl to handle the upload request to save the file to disk.

I checked the http upload example in the wizard demo and it works (although a little complicated.)

I'm wondering what is the correct way to reject a multipart form post request (to upload file). I tried to directly write response but the post data will continue passed in.

Later I got a way to do that, the detail is writing response and return false in servlet to close the connection, but in this way some time the client could not got response, I found I need to use ac_doze to wait some time to make sure the response "actually" write to client. This way acutally works but seems not a ideal way.

Is any way to handle this situation or there are any other way to correctly reject the upload request?

Thanks in advance.

**Comment by bladewhistle** [comment]
Some update:

I read through the http_client.cpp and I tried:

res.setContentEncoding(false).setChunkedTransferEncoding(false).setContentLength(buf.length());
res.write(buf);

return false;

With this way(disable gzip and chunk mode) I found the response data can successfully write to client. maybe in this way the fflush method will be called finally?

**Comment by zhengshuxin** [comment]
The client supports gzip and chunk transfer?
