### ISSUE TITLE
build error LNK2001: unresolved external symbol "public: virtual __thiscall acl::string::~string(void)"  

### ISSUE THREAD

**Issue by ScottKaiGu** [acl-dev/acl#18]
should be acl version 87, 修改历史列表：--87) 2015.5.21

---

source code in error:

```
const char* cmd = "ZREM"; 
std::vector<acl::string> args;
m_transaction.clear();
args.clear();

cmd = "ZREM";
args.push_back(GlobalRedisKeys::Instance()->m_key_zsetRegion.c_str());
args.push_back(cross_region_key.c_str());
if (m_transaction.run_cmd(cmd, args) == false) { //remove from  zset
    ROOT_LOGGER->error("redis: run cmd error! cmd: ZREM " + GlobalRedisKeys::Instance()->m_key_zsetRegion);
    return false;
}
```

ERROR:

> RMBussinessLogic.obj : error LNK2001: unresolved external symbol "public: virtual __thiscall acl::string::~string(void)" (??1string@acl@@UAE@XZ)

**Comment by zhengshuxin** [comment]
Do you link your program with the libraries of lib_acl, lib_protocol and lib_acl_cpp? And you can try to compile the samples of acl..
