### ISSUE TITLE
编译libacl_cpp.so出错

### ISSUE THREAD

**Issue by jialebifashi** [acl-dev/acl#182]
按照说明文档已经编译出acl与protocol的so库
但libacl_cpp.so时按照指导：还需要提前编译在 resource 目录下的 polarssl 库，编译完后再编译 libacl_cpp.so 同时需要指定 polarssl.lib 库所在的路径；如果不需要 SSL 通讯方式，则需要打开 lib_acl_cpp/Makefile 文件，去年编译选项：-DHAS_POLARSSL
我没找到polarssl库在哪里编译
略过polarssl直接编译libacl_cpp.so报错，显示如下
creating libacl_cpp.so
building for linux
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status

Makefile文件中看到了 shared_ldflags = -lprotocol -lacl -lrt -lpthread -lz -ldl请问这个-lz是指libz.so吗？
我在github上专门下了zlib编译然后libacl_cpp.so就OK了
请问这样没问题吗？

编译的时候lib_acl.hpp的包含头文件出现各种问题，我的用法是
   //我自己的.h文件中
   #ifndef _CMREDIS_
   #define _CMREDIS_
   //ACL Redis中间件分布式部署头文件
   #include "lib_acl.hpp"
   //我自己的类
   class RedisQueue
   {代码....}

编译的时候出现的错误如下:
In file included from /usr/include/c++/5/cstdio:42:0,
                 from /usr/include/c++/5/ext/string_conversions.h:43,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/istream:38,
                 from /home/Fred/libandfile/include/config.h:10,
                 from /home/Fred/libandfile/include/forwards.h:10,
                 from /home/Fred/libandfile/include/features.h:10,
                 from /usr/include/stdlib.h:24,
                 from /home/Fred/libandfile/include/acl_cpp/acl_cpp_define.hpp:33,
                 from /home/Fred/libandfile/include/acl_cpp/lib_acl.hpp:3,
                 from RedisQueue.h:6,
                 from RedisQueue.cpp:2:
/usr/include/stdio.h:195:8: error: ‘FILE’ does not name a type
 extern FILE *tmpfile (void) __wur;
        ^
/usr/include/stdio.h:237:20: error: ‘FILE’ was not declared in this scope
 extern int fclose (FILE *__stream);
                    ^
/usr/include/stdio.h:237:26: error: ‘__stream’ was not declared in this scope
 extern int fclose (FILE *__stream);
等等.... 基本都是从lib_acl.hpp文件内包含的头文件出问题

顺便我的编译命令是 
g++ SiftOnly.cpp FeatureFileIO.cpp FredProcess.cpp MySearchFile.cpp RedisQueue.cpp -std=c++11 -I. -I/home/Fred/libandfile/include -I/home/Fred/libandfile/include/acl -I/home/Fred/libandfile/include/acl_cpp -I/home/Fred/libandfile/include/acl_protocol -DNDEBUG -DLINUX2 -O3 -lpthread -ldl -o SiftOnly_Linux

请问是我少包含了什么东西吗？期待您的回复！！！！

谢谢！

**Comment by zhengshuxin** [comment]
编译 acl 应该没有您这么麻烦的，看来您是掉坑里了。-lz 是系统的 libz.a/libz.so，如果系统没有，可以从 https://github.com/acl-dev/third_party 处下载 acl 依赖的第三方库，除了 -lz 是必须的外，其它库都不是必须依赖的，除非你需要这些功能（比如：acl 要支持 ssl 时需要 polarssl, 支持 mysql 时也需要 mysql 库，等等）。
另外，为了方便编译和使用，acl 在使用 polarssl, mysql, sqlite, postgresql 时都是动态加载依赖库。
在 UNIX 平台编译 acl 非常简单，只需在 acl/ 目录运行: make 便会生成 libacl_all.a/libacl_all.so，通过 make packinstall 可以把 libacl_all.a 及头文件拷贝至系统目录。

**Comment by jialebifashi** [comment]
上面的问题已经解决了，跟acl没关系，我的是ubuntu16.04，三个so库是编出来了，但是想合成一个还是不行，在acl-master目录下输入make提示如下：
Makefile:207: recipe for target 'debug/dns.o' failed
make[2]: *** [debug/dns.o] Error 1
make[2]: Leaving directory '/home/Fred/open/src/acl-master/lib_fiber/c'
Makefile:9: recipe for target 'lib_fiber' failed
make[1]: *** [lib_fiber] Error 2
make[1]: Leaving directory '/home/Fred/open/src/acl-master/lib_fiber'
Makefile:87: recipe for target 'all_lib' failed
make: *** [all_lib] Error 2

**Comment by zhengshuxin** [comment]
如果你在 acl 目录下直接make 应该会生成 libacl_all.a 和 libacl_all.so，libacl_all 库是合并了 lib_acl, lib_protocol 和 libacl_cpp 三个库。
