### ISSUE TITLE
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值

### ISSUE THREAD

**Issue by keminar** [acl-dev/acl#184]
In file included from src/dns/dns.c:88:
src/dns/dns.c: 在函数‘dns_p_merge’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:1821:4: 附注：in expansion of macro ‘dns_rr_foreach’
 1821 |    dns_rr_foreach(&rr, A, .section = section) {
      |    ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:1828:4: 附注：in expansion of macro ‘dns_rr_foreach’
 1828 |    dns_rr_foreach(&rr, B, .section = section) {
      |    ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:1831:5: 附注：in expansion of macro ‘dns_rr_foreach’
 1831 |     dns_rr_foreach(&mr, M, .type = rr.type, .section = DNS_S_ALL) {
      |     ^~~~~~~~~~~~~~
src/dns/dns.c: 在函数‘dns_p_dump’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.c:2044:17: 附注：in expansion of macro ‘dns_rr_i_new’
 2044 |  dns_p_dump3(P, dns_rr_i_new(P, .section = 0), fp);
      |                 ^~~~~~~~~~~~
src/dns/dns.c: 在函数‘dns_m_study’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:2091:2: 附注：in expansion of macro ‘dns_rr_foreach’
 2091 |  dns_rr_foreach(&rr, P, .type = DNS_T_OPT, .section = DNS_S_AR) {
      |  ^~~~~~~~~~~~~~
src/dns/dns.c: 在函数‘dns_rr_exists’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:2851:2: 附注：in expansion of macro ‘dns_rr_foreach’
 2851 |  dns_rr_foreach(&rr1, P1, .section = rr0->section, .type = rr0->type) {
      |  ^~~~~~~~~~~~~~
src/dns/dns.c: 在函数‘dns_hints_query’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.c:6052:27: 附注：in expansion of macro ‘dns_rr_i_new’
 6052 |  if (!dns_rr_grep(&rr, 1, dns_rr_i_new(Q, .section = DNS_S_QUESTION), Q, &error))
      |                           ^~~~~~~~~~~~
src/dns/dns.c: 在函数‘dns_res_merge’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7272:2: 附注：in expansion of macro ‘dns_rr_foreach’
 7272 |  dns_rr_foreach(&rr[0], P[0], .section = DNS_S_QD) {
      |  ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7279:4: 附注：in expansion of macro ‘dns_rr_foreach’
 7279 |    dns_rr_foreach(&rr[i], P[i], .section = section) {
      |    ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7282:5: 附注：in expansion of macro ‘dns_rr_foreach’
 7282 |     dns_rr_foreach(&rr[2], P[2], .type = rr[i].type, .section = (DNS_S_ALL & ~DNS_S_QD)) {
      |     ^~~~~~~~~~~~~~
src/dns/dns.c: 在函数‘dns_res_glue’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7338:3: 附注：in expansion of macro ‘dns_rr_foreach’
 7338 |   dns_rr_foreach(&rr, R->stack[sp].answer, .name = qname, .type = qtype, .section = (DNS_S_ALL & ~DNS_S_QD)) {
      |   ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7354:3: 附注：in expansion of macro ‘dns_rr_foreach’
 7354 |   dns_rr_foreach(&rr, R->stack[sp].answer, .name = qname, .type = DNS_T_CNAME, .section = (DNS_S_ALL & ~DNS_S_QD)) {
      |   ^~~~~~~~~~~~~~
src/dns/dns.c: 在函数‘dns_res_nameserv_cmp’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.c:7389:35: 附注：in expansion of macro ‘dns_rr_i_new’
 7389 |   glued[0] = !!dns_rr_grep(&x, 1, dns_rr_i_new(P, .section = (DNS_S_ALL & ~DNS_S_QD), .name = ns.host, .type = DNS_T_A), P, &error);
      |                                   ^~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.c:7392:35: 附注：in expansion of macro ‘dns_rr_i_new’
 7392 |   glued[1] = !!dns_rr_grep(&y, 1, dns_rr_i_new(P, .section = (DNS_S_ALL & ~DNS_S_QD), .name = ns.host, .type = DNS_T_A), P, &error);
      |                                   ^~~~~~~~~~~~
src/dns/dns.c: 在函数‘dns_res_exec’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7442:3: 附注：in expansion of macro ‘dns_rr_foreach’
 7442 |   dns_rr_foreach(&rr, F->answer, .name = u.name, .type = dns_rr_type(12, F->query), .section = DNS_S_AN) {
      |   ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7446:3: 附注：in expansion of macro ‘dns_rr_foreach’
 7446 |   dns_rr_foreach(&rr, F->answer, .name = u.name, .type = DNS_T_CNAME, .section = DNS_S_AN) {
      |   ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7636:3: 附注：in expansion of macro ‘dns_rr_foreach’
 7636 |   dns_rr_foreach(&rr, F[1].answer, .name = u.host, .type = DNS_T_A, .section = (DNS_S_ALL & ~DNS_S_QD)) {
      |   ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7726:3: 附注：in expansion of macro ‘dns_rr_foreach’
 7726 |   dns_rr_foreach(&rr, F->answer, .section = DNS_S_AN, .name = u.name, .type = rr.type) {
      |   ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7730:3: 附注：in expansion of macro ‘dns_rr_foreach’
 7730 |   dns_rr_foreach(&rr, F->answer, .section = DNS_S_AN, .name = u.name, .type = DNS_T_CNAME) {
      |   ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7749:3: 附注：in expansion of macro ‘dns_rr_foreach’
 7749 |   dns_rr_foreach(&rr, F->answer, .section = DNS_S_NS, .type = DNS_T_NS) {
      |   ^~~~~~~~~~~~~~
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.h:573:53: 附注：in expansion of macro ‘dns_rr_i_new’
  573 |  for (struct dns_rr_i DNS_PP_XPASTE(i, __LINE__) = *dns_rr_i_new((P), __VA_ARGS__); dns_rr_grep((rr), 1, &DNS_PP_XPASTE(i, __LINE__), (P), &(int){ 0 }); )
      |                                                     ^~~~~~~~~~~~
src/dns/dns.h:575:29: 附注：in expansion of macro ‘dns_rr_foreach_’
  575 | #define dns_rr_foreach(...) dns_rr_foreach_(__VA_ARGS__)
      |                             ^~~~~~~~~~~~~~~
src/dns/dns.c:7874:3: 附注：in expansion of macro ‘dns_rr_foreach’
 7874 |   dns_rr_foreach(&rr, F[1].answer, .section = DNS_S_AN, .type = DNS_T_A) {
      |   ^~~~~~~~~~~~~~
src/dns/dns.c: 在函数‘dns_ai_nextent’中:
src/dns/dns.h:535:16: 错误：单目‘&’的操作数必须是左值
  535 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
      |                ^
src/dns/dns.c:8568:27: 附注：in expansion of macro ‘dns_rr_i_new’
 8568 |   if (dns_rr_grep(&rr, 1, dns_rr_i_new(ai->glue, .section = DNS_S_QD, .name = ai->g.name, .type = ai->g.type), ai->glue, &error))
      |                           ^~~~~~~~~~~~
make[2]: *** [Makefile:210：debug/dns.o] 错误 1

**Comment by keminar** [comment]
系统archlinux 最新

**Comment by zhengshuxin** [comment]
这个DNS模块是集成的模块，在用某些版本的 gcc 编译时确实是有问题的。该DNS模块地址参考：https://github.com/wahern/dns

**Comment by keminar** [comment]
那要如何处理，能给个方案不

**Comment by wii1980** [comment]
你是用的gcc 9编译的吧,换低版本gcc就可以.

**Comment by SPURSGO** [comment]
> 那要如何处理，能给个方案不

我用的用gcc-4.9就可以的。用如下命令指定make使用的gcc版本就可以了
make build_one CC=gcc-4.9 CPP=g++-4.9 CXX=g++-4.9 LD=g++-4.9

**Comment by zhengshuxin** [comment]
问题已经解决，完全重写了DNS功能模块，去掉了原来所依赖的第三方DNS库。
