### ISSUE TITLE
redis_client_cluster set_password coredump

### ISSUE THREAD

**Issue by lioncfliu** [acl-dev/acl#185]
hi:
acl is a nice tool. 
I got something wrong(coredump) when called redis_client_cluster.set_password function.
May I make some mistaks when used acl::redis_client_cluster ?

partial output of bt:
gdb) bt
#0  acl::locker::lock (this=0x418) at src/stdlib/locker.cpp:121
#1  0x00000000004d9ecf in acl::lock_guard::lock_guard (this=<optimized out>, lk=...) at src/stdlib/locker.cpp:208
#2  0x00000000004d34f9 in acl::redis_client_cluster::set_password (this=0x360, addr=0x18341d0 "\320s\v\001", pass=0x7fce9491c7c8 <main_arena+104> "0d\202\001")
    at src/redis/redis_client_cluster.cpp:188

![image](https://user-images.githubusercontent.com/16104565/68282822-539b7900-00b5-11ea-9b4b-36164fdd7695.png)

`
//source code of test_demo:（used acl-master）
int RedisClientWrapper::init()
{

    if (! reader_) {
        reader_ = new acl::redis_client_cluster();
        reader_->set(reader_address_.c_str(), max_connections_,
                     connection_timeout_, rw_timeout_);
    }
    if (! writer_) {
        writer_ = new acl::redis_client_cluster();
        writer_->set(writer_address_.c_str(), max_connections_,
                           connection_timeout_, rw_timeout_);
    }
    //coredumped from bellow:
    reader_->set_password(reader_address_.c_str(), auth_token_.c_str());
    writer_->set_password(writer_address_.c_str(), auth_token_.c_str());
    return kOk;
}
`

**Comment by zhengshuxin** [comment]
Which acl version are you using ?

**Comment by lioncfliu** [comment]
> Which acl version are you using ?
I am sorry ，I did not reply immediately.
My demo used acl-master ,just for testing.
