### ISSUE TITLE
class ACL_CPP_API redis_string->bool get(const char* key, string& buf); 内存泄露

### ISSUE THREAD

**Issue by solowolf** [acl-dev/acl#186]
void test_single_memleak()
{
	acl::acl_cpp_init();
	acl::string redis_addr("xxxx:6379");
	acl::redis_client client(redis_addr);
	client.set_password("123456");
	client.set_timeout(1, 1);
	acl::redis_string rclient;
	rclient.set_client(&client);

	for (int i = 0; i < 10000000; i++)
	{
		string skey = "get_cinfo";
		acl::string acl_value;
		rclient.get(skey.c_str(), acl_value);
		//cout << "sum:" << i << endl;
	}

}

key是一个1兆的字符串, 泄露很快.  不知道是不是用法问题.

**Comment by solowolf** [comment]
vs2008 32 release

**Comment by zhengshuxin** [comment]
在循环里复用一个命令对象（继承于 acl::redis_command 类）时，需要调用 clear()，比如你的例子中，需要在循环里调用： rcclient.clear().

**Comment by solowolf** [comment]
谢谢....

**Comment by ghost** [comment]
> 在循环里复用一个命令对象（继承于 acl::redis_command 类）时，需要调用 clear()，比如你的例子中，需要在循环里调用： rcclient.clear().

一般clear意思是清空一切缓存，包括连接池等等，所以个人感觉这个函数命名有歧义。
而且它到底是如何清空返回值缓冲区的也没注释清楚，源码很难懂，在实际使用时是不是必须每次都要清空一下？？那样是不是反复申请释放内存造成性能问题？

**Comment by zhengshuxin** [comment]
> 在实际使用时是不是必须每次都要清空一下

内部使用一个局部内存池，不会有性能问题，性能反而是非常高的。

**Comment by zhengshuxin** [comment]
> 
> 
> > 在循环里复用一个命令对象（继承于 acl::redis_command 类）时，需要调用 clear()，比如你的例子中，需要在循环里调用： rcclient.clear().
> 
> 一般clear意思是清空一切缓存，包括连接池等等，所以个人感觉这个函数命名有歧义。
> 而且它到底是如何清空返回值缓冲区的也没注释清楚，源码很难懂，在实际使用时是不是必须每次都要清空一下？？那样是不是反复申请释放内存造成性能问题？

内部使用一个局部内存池，不会有性能问题，性能反而是非常高的
