### ISSUE TITLE
acl::string.format("%u", uint64) issue

### ISSUE THREAD

**Issue by ScottKaiGu** [acl-dev/acl#19]
```
Boost::uint64_t timeInMs=1446202713817;
acl::string recvTimeInMilliSec;
recvTimeInMilliSec.format("%u", timeInMs); 
//recvTimeInMilliSec== "3093702361"
```

**Comment by zhengshuxin** [comment]
%u is 32 bits, and uint64_t is 64 bits, so, you should use it like "recvTimeInMilliSec.format("%llu", timeInMs);"

**Comment by ScottKaiGu** [comment]
in std::fprintf (http://en.cppreference.com/w/cpp/io/c/fprintf)  %u is for: 

unsigned char
unsigned short
unsigned int
unsigned long
unsigned long long
uintmax_t
size_t
unsigned version of ptrdiff_t

i think this can makes user confusing?
