### ISSUE TITLE
连接池为什么用一个vector存储和查找？？而且这个连接池是每个线程创建一套吧？如果多线程程序岂不是建很多连接？

### ISSUE THREAD

**Issue by ghost** [acl-dev/acl#190]
如题，谢谢

**Comment by ghost** [comment]
不然单机要开很多连接。

**Comment by ghost** [comment]
比如200台主机，单机是20线程，这样单机岂不是大约200*20个连接？？

**Comment by ghost** [comment]
redis_client_cluster::set_slot 和 connect_pool* connect_manager::get这两个函数真是不敢恭维，不明白为啥这么写。

**Comment by zhengshuxin** [comment]
acl 里的连接池本来就是线程内共享的。不是每个线程一个连接池，具体可以看看头文件和例子。

**Comment by ghost** [comment]
> acl 里的连接池本来就是线程内共享的。不是每个线程一个连接池，具体可以看看头文件和例子。

线程内共享不就是一个线程一个吗？这段代码不就是这样吗？？
	manager_it mit = manager_.find(id);
	if (mit != manager_.end()) {
		return *mit->second;
	}

	conns_pools* pools  = new conns_pools;
	manager_[id] = pools;
	//printf("thread id=%lu create pools, %lu\r\n", id, pthread_self());

**Comment by wii1980** [comment]
> > acl 里的连接池本来就是线程内共享的。不是每个线程一个连接池，具体可以看看头文件和例子。
> 
> 线程内共享不就是一个线程一个吗？这段代码不就是这样吗？？
> manager_it mit = manager_.find(id);
> if (mit != manager_.end()) {
> return *mit->second;
> }
> 
> ```
> conns_pools* pools  = new conns_pools;
> manager_[id] = pools;
> //printf("thread id=%lu create pools, %lu\r\n", id, pthread_self());
> ```

要看全面,不要盲人摸象.  get_id()!

**Comment by ghost** [comment]
> acl 里的连接池本来就是线程内共享的。不是每个线程一个连接池，具体可以看看头文件和例子。

我的意思是删掉整个issue，谢谢！
