### ISSUE TITLE
linux编译动态库问题。

### ISSUE THREAD

**Issue by ghost** [acl-dev/acl#191]
lib_protocol.so和lib_acl_cpp.so两个库会依赖lib_acl.so，但是makefile里写的是-lacl -lprotocol，不知道怎么测的，而且linux redhat系列的都有个/lib64/libacl.so的库，这样就完全关联错了！！！

**Comment by zhengshuxin** [comment]
你可以在acl项目下直接make，会生成一个 libacl_all.so 和 libacl_all.a

**Comment by ghost** [comment]
> 你可以在acl项目下直接make，会生成一个 libacl_all.so 和 libacl_all.a

关键有的功能用不到啊

**Comment by zhengshuxin** [comment]
libacl_all 就已经包含了 lib_acl, lib_protocol, lib_acl_cpp 的所有功能，你还需要什么关键功能 ？

**Comment by ghost** [comment]
> libacl_all 就已经包含了 lib_acl, lib_protocol, lib_acl_cpp 的所有功能，你还需要什么关键功能 ？

我的意思是最多就用这几个包，其他的我用不到！

**Comment by ghost** [comment]
> libacl_all 就已经包含了 lib_acl, lib_protocol, lib_acl_cpp 的所有功能，你还需要什么关键功能 ？

请帮忙删掉这个issue吧，你也没明白我什么意思。
