### ISSUE TITLE
在 Windows 10 下使用 CMAKE 编译时出现错误。

### ISSUE THREAD

**Issue by zh1an** [acl-dev/acl#195]
你好，新年好呀！
这两天我使用微软推出的 `vcpkg` 工具编译 `ACL` 动态库的时候发现，在 Windows 平台总是出现链接错误。比如下边的这种：
```
[D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
         http_chat_async.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_warn [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
         http_hdr_req.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_warn [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
         smtp_client.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_warn [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
         icmp_chat_aio.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_warn [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
         icmp_pkt.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_error [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
         icmp_stream.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_error [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
         http_hdr_res.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_error [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
......
```
我知道这是链接错误，我就在 `CMakeLists.txt` 中查找，就发现了这样三句话：
``` cmake
SET_TARGET_PROPERTIES(acl_static PROPERTIES OUTPUT_NAME "acl")
SET_TARGET_PROPERTIES(protocol_static PROPERTIES OUTPUT_NAME "protocol")
SET_TARGET_PROPERTIES(acl_cpp_static PROPERTIES OUTPUT_NAME "acl_cpp")
```
这句话是必须要的吗？

当开启编译动态库选项的时候，静态库总是比动态库先编译，而动态库编译之后就会覆盖之前的静态库，造成后续编译其他的库的时候就会出现链接错误。

**Comment by zhengshuxin** [comment]
在WIN平台下，acl 提供了专门的 vs 工程，不必从 cmake 中生成工程文件。不过我也会检查一下 cmake 工程在 win 下的问题，谢谢。

**Comment by zhengshuxin** [comment]
> 
> 
> 你好，新年好呀！
> 这两天我使用微软推出的 `vcpkg` 工具编译 `ACL` 动态库的时候发现，在 Windows 平台总是出现链接错误。比如下边的这种：
> 
> ```
> [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
>          http_chat_async.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_warn [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
>          http_hdr_req.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_warn [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
>          smtp_client.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_warn [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
>          icmp_chat_aio.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_warn [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
>          icmp_pkt.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_error [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
>          icmp_stream.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_error [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
>          http_hdr_res.obj : error LNK2001: 无法解析的外部符号 __imp__acl_msg_error [D:\git\vcpkg\buildtrees\acl\x86-windows-rel\protocol\protocol.vcxproj]
> ......
> ```
> 
> 我知道这是链接错误，我就在 `CMakeLists.txt` 中查找，就发现了这样三句话：
> 
> ```cmake
> SET_TARGET_PROPERTIES(acl_static PROPERTIES OUTPUT_NAME "acl")
> SET_TARGET_PROPERTIES(protocol_static PROPERTIES OUTPUT_NAME "protocol")
> SET_TARGET_PROPERTIES(acl_cpp_static PROPERTIES OUTPUT_NAME "acl_cpp")
> ```
> 
> 这句话是必须要的吗？
> 
> 当开启编译动态库选项的时候，静态库总是比动态库先编译，而动态库编译之后就会覆盖之前的静态库，造成后续编译其他的库的时候就会出现链接错误。

可能你的cmake工程文件需要更新一下了，在当前的cmake文件中已经没有这三行了。另外，在编译动态库时需要注意以下两点：
1、指定编译选项：ACL_BUILD_SHARED=YES
2、注意编译顺序：acl-->protocol-->acl_cpp
