### ISSUE TITLE
请教：win10 64位 debug模式 使用例子redis_hash错误

### ISSUE THREAD

**Issue by fwj514551450** [acl-dev/acl#196]
错误如图：

![未命名1581049846](https://user-images.githubusercontent.com/37462824/74001235-c57daa00-49a5-11ea-83d0-4161c1ed738f.png)

而在release可以正常运行，请问有人遇到过类似的问题吗？

**Comment by fwj514551450** [comment]
测试了几个函数，发现只要涉及map、list、vector等容器的都出现崩溃

**Comment by zhengshuxin** [comment]
> 
> 
> 测试了几个函数，发现只要涉及map、list、vector等容器的都出现崩溃

有具体的栈信息吗？

**Comment by zhengshuxin** [comment]
另外，我测试了64位的例子：acl\lib_acl_cpp\samples\redis\redis_hash，测试结果是正确的，没有出现崩溃现象。不知道你是如何测的？

**Comment by fwj514551450** [comment]
![image](https://user-images.githubusercontent.com/37462824/74585671-2d716780-501a-11ea-96af-8f2426919d33.png)

是要这个调试堆栈信息吗？  
我使用的例子是 redis_hash.cpp  
指令是：all

**Comment by fwj514551450** [comment]
我只是将其生成为动态库之后，然后直接跑测试例子（acl\lib_acl_cpp\samples\redis\redis_hash）；只有是获取数组的函数才会出现崩溃现象，而且是在整个函数结束尾部才会崩溃

**Comment by fwj514551450** [comment]
![image](https://user-images.githubusercontent.com/37462824/74588592-c6af7680-5038-11ea-91a2-77684af611fb.png)
执行到释放map的时候就会出现崩溃（debug模式）

**Comment by fwj514551450** [comment]
我将运行库从MTd->MDd 就不会出现这个错误了。虽然不知道原理是什么，但是总算是可以使用了

**Comment by zhengshuxin** [comment]
是的，该问题已经确认，并在 vc2012 中的工程中进行了修复。
谢谢。
--zsx
