### ISSUE TITLE
在macOS 10.15下编译出现错误

### ISSUE THREAD

**Issue by luwei08** [acl-dev/acl#198]
errorerror: : error: unknown warning option unknown'-Wno-extended-offsetof';unknown   didwarningwarning   optionyouoption   '-Wno-extended-offsetof';mean'-Wno-extended-offsetof'; 
 did      did '-Wno-invalid-offsetof'? youyou   [-Werror,-Wunknown-warning-option]meanmean

      
      '-Wno-invalid-offsetof'?'-Wno-invalid-offsetof'?  [-Werror,-Wunknown-warning-option][-Werror,-Wunknown-warning-option]

**Comment by zhengshuxin** [comment]
I think I've fixed the compiling problem on some MacOS.
Thanks.
--zsx

**Comment by pbdm** [comment]
got same error on macOS 10.15.13
`building src/acl_fstream.cpp`
`error: unknown warning option '-Wno-extended-offsetof'; did you mean '-Wno-invalid-offsetof'? [-Werror,-Wunknown-warning-option]`
`make[1]: *** [Debug/acl_fstream.o] Error 1`
`make: *** [all_lib] Error 2`
