### ISSUE TITLE
Ignore more Irrelevant files

### ISSUE THREAD

**Issue by xuchunyang** [acl-dev/acl#2]
The repo is about 106M:

```
➜  acl git:(master) du -sh
106M    .
```

I think It's unnecessary to let `Git` to track library files, i.e. `*.dll` for WIN, `*.a"` for Linux, and in addition IDE specific project configure files like `acl_vc2003.sln` should be ignored too.

**Comment by zhengshuxin** [comment]
Yes, you're right. Later, I'll remove the .a and *.dll from acl. Thanks.

**Comment by xuchunyang** [comment]
Thank you for the work! :smile:
