### ISSUE TITLE
redhat6.5操作系统，升级GCC到6.1.0，然后使用zrangebyscore，查询数量大时，必崩

### ISSUE THREAD

**Issue by wangjk91** [acl-dev/acl#201]
redhat6.5操作系统，升级GCC到6.1.0，然后使用zrangebyscore，查询数量大于500时，然后必崩。
同样的代码，在redhat7.4则没问题，gcc版本也为6.1.0。
然后只要崩溃一次后，查询数量为1时，也崩溃。

#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <vector>
#include "acl_cpp/lib_acl.hpp"
#define TEST_KEY "mytest"
void test_insert(acl::redis_zset* pzset,uint32_t n)
{
        std::string zkey;
        zkey = TEST_KEY;
        int num = 0;
        std::map<acl::string, double> members;
        acl::string member;
        uint32_t ret = 0;
        while(num<n)
        {
                members.clear();
                member.clear();
                member.format("%d",num);
                time_t t = time(NULL);
                members[member] = t;
                ret = pzset->zadd(zkey.c_str(),members);
                printf("zadd key:%s member:%s score:%ld result:%d\n",zkey.c_str(),member.c_str(),
                        t,ret);
                usleep(10*1000);
                num++;
        }
}
void test_get(acl::redis_zset* pzset)
{
        std::vector<acl::string> result;
        int ret = pzset->zrangebyscore(TEST_KEY,1,time(NULL),&result);
        printf("test_get key:%s ret:%d\n",TEST_KEY,ret);
}
int main(int argc,char* argv[])
{
        if(argc<2)
        {
                printf("please input test num!ps: %s number\n",argv[0]);
                return 0;
        }
        acl::redis_client_cluster cluster;
        cluster.set("10.79.144.101:7000",1);
        cluster.set_password("default","123456");
        acl::redis_zset zset;
        zset.set_cluster(&cluster,1);
        test_insert(&zset,atoi(argv[1]));
        test_get(&zset);
        getchar();
        return 0;
}

**Comment by zhengshuxin** [comment]
> redhat6.5操作系统，升级GCC到6.1.0，然后使用zrangebyscore，查询数量大于500时，然后必崩。
> 同样的代码，在redhat7.4则没问题，gcc版本也为6.1.0。
> 然后只要崩溃一次后，查询数量为1时，也崩溃。
> 
> #include <stdio.h>
> #include <unistd.h>
> #include <stdlib.h>
> #include
> #include "acl_cpp/lib_acl.hpp"
> #define TEST_KEY "mytest"
> void test_insert(acl::redis_zset* pzset,uint32_t n)
> {
> std::string zkey;
> zkey = TEST_KEY;
> int num = 0;
> std::map<acl::string, double> members;
> acl::string member;
> uint32_t ret = 0;
> while(num<n)
> {
> members.clear();
> member.clear();
> member.format("%d",num);
> time_t t = time(NULL);
> members[member] = t;
> ret = pzset->zadd(zkey.c_str(),members);
> printf("zadd key:%s member:%s score:%ld result:%d\n",zkey.c_str(),member.c_str(),
> t,ret);
> usleep(10_1000); num++; } } void test_get(acl::redis_zset_ pzset)
> {
> std::vectoracl::string result;
> int ret = pzset->zrangebyscore(TEST_KEY,1,time(NULL),&result);
> printf("test_get key:%s ret:%d\n",TEST_KEY,ret);
> }
> int main(int argc,char* argv[])
> {
> if(argc<2)
> {
> printf("please input test num!ps: %s number\n",argv[0]);
> return 0;
> }
> acl::redis_client_cluster cluster;
> cluster.set("10.79.144.101:7000",1);
> cluster.set_password("default","123456");
> acl::redis_zset zset;
> zset.set_cluster(&cluster,1);
> test_insert(&zset,atoi(argv[1]));
> test_get(&zset);
> getchar();
> return 0;
> }

麻烦你先提供一个可编译的代码，你上面提供的代码无法通过编译。
