### ISSUE TITLE
qt 使用acl 全局指针获取线程池内的连接  获取不到。崩溃

### ISSUE THREAD

**Issue by jiasondouble** [acl-dev/acl#202]
根据demo修改，增加一个类。redis_con  全家变量 g_redis_c 
class redis_con()
{
    acl::redis_client_pool& pool_
    redis_con::redis_con(acl::redis_client_pool& pool):pool_(pool)
   {

   }
    acl::redis_client* redis_con::get_conn()
    {
    acl::redis_client* conn= nullptr;
    conn = (acl::redis_client*) pool_.peek();//全局使用崩溃。
    if (conn == nullptr)
    {
        printf("peek redis connection error\r\n");
        return conn= nullptr;
    }
    else
    {
        return  conn;
    }
     }
}

test()
{
 acl::redis_client* conn = g_redis_c->get_conn();
/////这句出现崩溃
}
void redis_pool(const char* redis_addr, int max_threads,int conn_timeout, int rw_timeout)
{
    acl::redis_client_pool pool(redis_addr, max_threads);
    pool.set_timeout(conn_timeout, rw_timeout);
    g_redis_c = new redis_con(pool);
//如果在这个函数里面使用g_redis_c.get_conn()就正常。
}
main
{
redis_poo(*,*,*,*)
test()
}
请求帮忙解答一下。谢谢！

**Comment by zhengshuxin** [comment]
你调用 peek 时不会是 redis_pool() 函数已经返回了吧
