### ISSUE TITLE
GCC7.3.0环境下使用redis，必挂

### ISSUE THREAD

**Issue by zombie5310** [acl-dev/acl#206]
崩溃位置位于redis_result.cpp 251行如下代码
for (size_t i = 0; i < children_idx_; i++)
{
	children[i] = children_[i];
}
发现如下现象：
1、gdb调试 i会设置两次0；
2、在循环内添加输出，不会崩溃
3、添加判断条件i < 1000000 不会崩溃。

将Makefile 中-O3改为 -O0，能运行，不知道此种方法功能是否正常？

**Comment by zhengshuxin** [comment]
行号对不上了，请用当前主干再试一下。
