### ISSUE TITLE
redis_trans error

### ISSUE THREAD

**Issue by songziqin** [acl-dev/acl#208]
my redis is  cluster model, and I want to use trans and when I test my code, I found redis.multi() is ok,
and the code redis.run_cmd is false, and I check the log, run_cmd the message is Ok not QUEUE,
so does acl redis client  support cluster trans..

**Comment by zhengshuxin** [comment]
Acl redis client can't handle multiple keys in one redis command, so, if you use redis trans with multiple keys it'll be failed.

**Comment by songziqin** [comment]
如果在一个事务里面我不可以对不同的KEY进行操作，那事务是不是就意义不大了，我这边主要想提高请求处理的效率，所以想到了事务。问下，还有什么法子可以提高请求处理的效率末，比如一次请求处理10000个KEY。现在的做法是一个一个的请求处理

> Acl redis client can't handle multiple keys in one redis command, so, if you use redis trans with multiple keys it'll be failed.
