### ISSUE TITLE
acl_vstring_base64_decode函数偶尔闪退

### ISSUE THREAD

**Issue by baimengwei** [acl-dev/acl#211]
```
	printf("4");
	//logger_error("error message:%d\r\n", (int)strlen(STR(node->text)));
	if (acl_vstring_base64_decode(Data_Row, (const char *)STR(node->text), (int)strlen(STR(node->text))) == 0)
	{
		printf("bad base64 encoded string: %s\r\n", STR(node->text));
		getchar();
		exit(1);
	}
	printf("5");
```
在10个进程的循环调用过程中，大概10分钟以后，控制台输出了4以后就终止了程序，**没有任何其它信息输出**。所以哪里存在问题吗。
另外，之前在传入参数过程中strlen(STR(node->text))没有int强制转换，则输出的bad base64 encoded string。
入参STR(node->text)为长度约为3000的字符串，从json中取出。

感谢。

**Comment by zhengshuxin** [comment]
写了一个demo， https://github.com/acl-dev/demo/tree/master/c/code   可以参考一下，没遇到你所说问题。

**Comment by baimengwei** [comment]
感谢回复。问题出在我程序的其它部分。
