### ISSUE TITLE
redis_key调用scan程序崩溃

### ISSUE THREAD

**Issue by JXT-Eden** [acl-dev/acl#221]
redis_key使用scan遍历redis key，程序崩溃，调用其它方法没有问题

**Comment by JXT-Eden** [comment]
![1](https://user-images.githubusercontent.com/9624017/99765675-84244880-2b3a-11eb-991d-24242a184d51.png)
redis_key中scan里面调用redis_commad里的scan_keys，参数key传递的为NULL
![2](https://user-images.githubusercontent.com/9624017/99765686-87b7cf80-2b3a-11eb-80eb-3afe65004f5c.png)
在redis_command里面scan_keys使用strlen(key)造成崩溃
修改为（NULL==KEY)?0:strlen(key)正常

**Comment by zhengshuxin** [comment]
谢谢提醒，不过该问题已经在10.30日的master主干中修复，请更新主干代码。
