### ISSUE TITLE
redis_client eof返回状态错误

### ISSUE THREAD

**Issue by JXT-Eden** [acl-dev/acl#222]
redis_client对象初始化后调用eof返回状态正确；传递给redis_key后，使用redis_client调用eof返回状态错误；使用redis_connection调用ping返回正确

**Comment by zhengshuxin** [comment]
redis_client 为单一连接对象，在初始化后其并未与 redis-server 建立 TCP 连接，故 eof() 返回 true，当将该连接对象与 redis 命令对象（如：redis_key）绑定并在命令对象操作完后再检查 eof() 会返回 false，原因是 redis_client 在被 redis_key 命令使用时与 redis-server 建立了连接。
