### ISSUE TITLE
Incorporating acl-redis client into a running project in C++

### ISSUE THREAD

**Issue by Sabyn1975** [acl-dev/acl#225]
I'm trying to include using acl-redis into one of my Projects TD_SvgExport. I had successfully built the lib_acl, lib_protocol and lib_acl_cpp modules within my solution in the same order. I've also added the ..\lib_acl\include;..and \lib_acl_cpp\include directory paths in Configuration Properties>C/C++>General>Additional Include Directories and lib_acl_vc2012.lib & lib_acl_cpp_vc2012.lib library files in Linker>Input>Additional Dependencies of my project. (I'm compiling the solution in Active(Release) configuration). Still I'm getting the below linker errors: What am I missing?

1>------ Rebuild All started: Project: TD_2dExport, Configuration: Release x64 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(346,5): warning MSB8004: Output Directory does not end with a trailing slash.  This build instance will add the slash as it is required to allow proper evaluation of the Output Directory.
1>  2dExportDevice.cpp
1>  2dSupport.cpp
1>  Generating Code...
1>  TD_2dExport.vcxproj -> F:\Projects\Panorama API\Teigha SVG Conversion\19.5\x64 - Redis\Package2019_x64\Platforms\vc11_amd64dll\SVGConversionx64\TD_2dExport\..\..\..\..\lib\vc11_amd64dll\TD_2dExport.lib
2>------ Rebuild All started: Project: TD_SvgExport, Configuration: Release x64 ------
2>  StdAfx_SvgExport.cpp
2>  SvgExport.cpp
2>..\..\..\..\Kernel\Exports\SvgExport\Source\SvgExport.cpp(604): warning C4101: 'e' : unreferenced local variable
2>  Generating Code...
2>     Creating library ..\..\..\..\lib\vc11_amd64dll\TD_SvgExport.lib and object ..\..\..\..\lib\vc11_amd64dll\TD_SvgExport.exp
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl acl::string::string(char const *)" (__imp_??0string@acl@@QEAA@PEBD@Z) referenced in function "public: static void __cdecl TD_SVG_EXPORT::OdSvgDevice::test_redis_string(class acl::redis_string &,char const *,char const *)" (?test_redis_string@OdSvgDevice@TD_SVG_EXPORT@@SAXAEAVredis_string@acl@@PEBD1@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl acl::string::~string(void)" (__imp_??1string@acl@@UEAA@XZ) referenced in function "public: static void __cdecl TD_SVG_EXPORT::OdSvgDevice::test_redis_string(class acl::redis_string &,char const *,char const *)" (?test_redis_string@OdSvgDevice@TD_SVG_EXPORT@@SAXAEAVredis_string@acl@@PEBD1@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char * __cdecl acl::string::c_str(void)const " (__imp_?c_str@string@acl@@QEBAPEADXZ) referenced in function "public: static void __cdecl TD_SVG_EXPORT::OdSvgDevice::test_redis_string(class acl::redis_string &,char const *,char const *)" (?test_redis_string@OdSvgDevice@TD_SVG_EXPORT@@SAXAEAVredis_string@acl@@PEBD1@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class acl::string & __cdecl acl::string::clear(void)" (__imp_?clear@string@acl@@QEAAAEAV12@XZ) referenced in function "public: static void __cdecl TD_SVG_EXPORT::OdSvgDevice::test_redis_string(class acl::redis_string &,char const *,char const *)" (?test_redis_string@OdSvgDevice@TD_SVG_EXPORT@@SAXAEAVredis_string@acl@@PEBD1@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl acl::connect_manager::set(char const *,unsigned __int64,int,int)" (__imp_?set@connect_manager@acl@@QEAAXPEBD_KHH@Z) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl TD_SVG_EXPORT::OdSvgDevice::postProcessTraverse(class OdString)" (?postProcessTraverse@OdSvgDevice@TD_SVG_EXPORT@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VOdString@@@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl acl::redis_client_cluster::redis_client_cluster(int)" (__imp_??0redis_client_cluster@acl@@QEAA@H@Z) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl TD_SVG_EXPORT::OdSvgDevice::postProcessTraverse(class OdString)" (?postProcessTraverse@OdSvgDevice@TD_SVG_EXPORT@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VOdString@@@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl acl::redis_client_cluster::~redis_client_cluster(void)" (__imp_??1redis_client_cluster@acl@@UEAA@XZ) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl TD_SVG_EXPORT::OdSvgDevice::postProcessTraverse(class OdString)" (?postProcessTraverse@OdSvgDevice@TD_SVG_EXPORT@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VOdString@@@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class acl::redis_client_cluster & __cdecl acl::redis_client_cluster::set_password(char const *,char const *)" (__imp_?set_password@redis_client_cluster@acl@@QEAAAEAV12@PEBD0@Z) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl TD_SVG_EXPORT::OdSvgDevice::postProcessTraverse(class OdString)" (?postProcessTraverse@OdSvgDevice@TD_SVG_EXPORT@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VOdString@@@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl acl::redis_command::clear(bool)" (__imp_?clear@redis_command@acl@@QEAAX_N@Z) referenced in function "public: static void __cdecl TD_SVG_EXPORT::OdSvgDevice::test_redis_string(class acl::redis_string &,char const *,char const *)" (?test_redis_string@OdSvgDevice@TD_SVG_EXPORT@@SAXAEAVredis_string@acl@@PEBD1@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl acl::redis_command::set_cluster(class acl::redis_client_cluster *,unsigned __int64)" (__imp_?set_cluster@redis_command@acl@@QEAAXPEAVredis_client_cluster@2@_K@Z) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl TD_SVG_EXPORT::OdSvgDevice::traverseID(struct TD_SVG_EXPORT::xml::Node *,int,class OdString,int &,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class acl::redis_client_cluster *,unsigned __int64)" (?traverseID@OdSvgDevice@TD_SVG_EXPORT@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAUNode@xml@2@HVOdString@@AEAH_NV34@PEAVredis_client_cluster@acl@@_K@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl acl::redis_key::redis_key(void)" (__imp_??0redis_key@acl@@QEAA@XZ) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl TD_SVG_EXPORT::OdSvgDevice::traverseID(struct TD_SVG_EXPORT::xml::Node *,int,class OdString,int &,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class acl::redis_client_cluster *,unsigned __int64)" (?traverseID@OdSvgDevice@TD_SVG_EXPORT@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAUNode@xml@2@HVOdString@@AEAH_NV34@PEAVredis_client_cluster@acl@@_K@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl acl::redis_key::`vbase destructor'(void)" (__imp_??_Dredis_key@acl@@QEAAXXZ) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl TD_SVG_EXPORT::OdSvgDevice::traverseID(struct TD_SVG_EXPORT::xml::Node *,int,class OdString,int &,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class acl::redis_client_cluster *,unsigned __int64)" (?traverseID@OdSvgDevice@TD_SVG_EXPORT@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAUNode@xml@2@HVOdString@@AEAH_NV34@PEAVredis_client_cluster@acl@@_K@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl acl::redis_string::redis_string(void)" (__imp_??0redis_string@acl@@QEAA@XZ) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl TD_SVG_EXPORT::OdSvgDevice::traverseID(struct TD_SVG_EXPORT::xml::Node *,int,class OdString,int &,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class acl::redis_client_cluster *,unsigned __int64)" (?traverseID@OdSvgDevice@TD_SVG_EXPORT@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAUNode@xml@2@HVOdString@@AEAH_NV34@PEAVredis_client_cluster@acl@@_K@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl acl::redis_string::set(char const *,char const *)" (__imp_?set@redis_string@acl@@QEAA_NPEBD0@Z) referenced in function "public: static void __cdecl TD_SVG_EXPORT::OdSvgDevice::test_redis_string(class acl::redis_string &,char const *,char const *)" (?test_redis_string@OdSvgDevice@TD_SVG_EXPORT@@SAXAEAVredis_string@acl@@PEBD1@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl acl::redis_string::get(char const *,class acl::string &)" (__imp_?get@redis_string@acl@@QEAA_NPEBDAEAVstring@2@@Z) referenced in function "public: static void __cdecl TD_SVG_EXPORT::OdSvgDevice::test_redis_string(class acl::redis_string &,char const *,char const *)" (?test_redis_string@OdSvgDevice@TD_SVG_EXPORT@@SAXAEAVredis_string@acl@@PEBD1@Z)
2>SvgExport.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl acl::redis_string::`vbase destructor'(void)" (__imp_??_Dredis_string@acl@@QEAAXXZ) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl TD_SVG_EXPORT::OdSvgDevice::traverseID(struct TD_SVG_EXPORT::xml::Node *,int,class OdString,int &,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class acl::redis_client_cluster *,unsigned __int64)" (?traverseID@OdSvgDevice@TD_SVG_EXPORT@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAUNode@xml@2@HVOdString@@AEAH_NV34@PEAVredis_client_cluster@acl@@_K@Z)
2>..\..\..\..\exe\vc11_amd64dll\TD_SvgExport_19.5_11.tx : fatal error LNK1120: 16 unresolved externals
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

**Comment by zhengshuxin** [comment]
Seem that your project is in DLL mode but you're using acl with static library, so you'd build DLLs of acl and add them into your project, and add "ACL_CPP_DLL" compiline macro define in your project. Some samples can be found in acl\lib_acl_cpp\samples\redis\redis.
