### ISSUE TITLE
vs2015无法编译dll

### ISSUE THREAD

**Issue by JXT-Eden** [acl-dev/acl#226]
最新master在vs2015编译修改为dll，默认为lib，无法编译，是修改工程配置了吗，之前的可以

**Comment by zhengshuxin** [comment]
我试了一下，用2005是可以编译为dll的。

**Comment by JXT-Eden** [comment]
lib_acl可以编译dll，但是没有lib。lib_acl_cpp lib_acl_protocl编译错误：
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1193,5): warning MSB8030: The linker switch "Minimum Required Version" requires "SubSystem" to be set.  Without "SubSystem", the "Minimum Required Version" would not be passed to linker and could prevent to the output binary from running on older Operating Systems.
1>smtp_client.obj : error LNK2019: 无法解析的外部符号 _acl_msg_warn，该符号在函数 _smtp_ehlo 中被引用
1>http_chat_async.obj : error LNK2001: 无法解析的外部符号 _acl_msg_warn
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_msg_warn
1>icmp_chat_aio.obj : error LNK2001: 无法解析的外部符号 _acl_msg_warn
1>icmp_pkt.obj : error LNK2001: 无法解析的外部符号 _acl_msg_warn
1>icmp_stream.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>icmp_chat_sio.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>icmp_pkt.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>http_chat_async.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>http_chat_sync.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>http_hdr.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_msg_error
1>icmp_stream.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>http_tmpl.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>icmp_chat.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>icmp_chat_aio.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>icmp_host.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>http_req.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>http_res.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>http_chat_async.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>http_chat_sync.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>http_hdr.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_msg_fatal
1>icmp_chat.obj : error LNK2019: 无法解析的外部符号 _acl_last_serror，该符号在函数 _icmp_chat_create 中被引用
1>icmp_chat_sio.obj : error LNK2001: 无法解析的外部符号 _acl_last_serror
1>icmp_stream.obj : error LNK2001: 无法解析的外部符号 _acl_last_serror
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_last_serror
1>http_chat_async.obj : error LNK2001: 无法解析的外部符号 _acl_last_serror
1>http_hdr.obj : error LNK2001: 无法解析的外部符号 _acl_last_serror
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_last_serror
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_last_serror
1>icmp_pkt.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>icmp_stream.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>icmp_timer.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>http_res.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>icmp_chat.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>icmp_host.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>http_chat_async.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>http_chat_sync.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>http_hdr.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>http_req.obj : error LNK2001: 无法解析的外部符号 _acl_calloc_glue
1>icmp_timer.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>icmp_chat_sio.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>icmp_host.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>icmp_pkt.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>icmp_stream.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>http_req.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>http_res.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>icmp_chat_aio.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>http_chat_async.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>http_chat_sync.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>http_hdr.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_free_glue
1>http_chat_async.obj : error LNK2019: 无法解析的外部符号 _acl_aio_ctl，该符号在函数 _hdr_get_async 中被引用
1>icmp_chat_aio.obj : error LNK2001: 无法解析的外部符号 _acl_aio_ctl
1>http_chat_async.obj : error LNK2019: 无法解析的外部符号 _acl_aio_vstream，该符号在函数 _hdr_get_async 中被引用
1>icmp_chat_aio.obj : error LNK2001: 无法解析的外部符号 _acl_aio_vstream
1>http_chat_async.obj : error LNK2019: 无法解析的外部符号 _acl_aio_gets_peek，该符号在函数 _chunked_data_endl 中被引用
1>http_chat_async.obj : error LNK2019: 无法解析的外部符号 _acl_aio_gets_nonl_peek，该符号在函数 _hdr_can_read 中被引用
1>http_chat_async.obj : error LNK2019: 无法解析的外部符号 _acl_aio_read_peek，该符号在函数 _chunked_data 中被引用
1>http_chat_async.obj : error LNK2019: 无法解析的外部符号 _acl_aio_readn_peek，该符号在函数 _chunked_data 中被引用
1>http_chat_async.obj : error LNK2019: 无法解析的外部符号 _acl_aio_enable_read，该符号在函数 _hdr_can_read 中被引用
1>http_chat_async.obj : error LNK2019: 无法解析的外部符号 _acl_aio_can_read，该符号在函数 _hdr_can_read 中被引用
1>http_chat_async.obj : error LNK2019: 无法解析的外部符号 _acl_aio_disable_read，该符号在函数 _hdr_can_read 中被引用
1>http_chat_sync.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_gets，该符号在函数 _chunked_hdr_get 中被引用
1>http_tmpl.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_gets
1>http_chat_sync.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_gets_nonl，该符号在函数 _hdr_get 中被引用
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_gets_nonl
1>http_chat_sync.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_read，该符号在函数 _chunked_data_get 中被引用
1>icmp_chat_sio.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_read
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_read
1>http_chat_sync.obj : error LNK2019: 无法解析的外部符号 _acl_msg_panic，该符号在函数 _http_chat_sync_reqctl 中被引用
1>http_tmpl.obj : error LNK2001: 无法解析的外部符号 _acl_last_strerror
1>http_chat_sync.obj : error LNK2001: 无法解析的外部符号 _acl_last_strerror
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_last_strerror
1>http_req.obj : error LNK2001: 无法解析的外部符号 _acl_last_strerror
1>http_res.obj : error LNK2001: 无法解析的外部符号 _acl_last_strerror
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_array_create，该符号在函数 _http_hdr_new 中被引用
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_array_create
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_array_create
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_array_clean，该符号在函数 _http_hdr_reset 中被引用
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_array_free，该符号在函数 _http_hdr_free 中被引用
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_array_free
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_array_free
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_array_append，该符号在函数 _http_hdr_append_entry 中被引用
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_array_delete_obj，该符号在函数 _http_hdr_entry_replace 中被引用
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_array_index，该符号在函数 _http_hdr_clone 中被引用
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_array_index
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_array_index
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_array_index
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_array_size，该符号在函数 _http_hdr_clone 中被引用
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_array_size
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_array_size
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_array_size
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_alloc
1>http_hdr.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_alloc
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_alloc
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_alloc
1>http_tmpl.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_alloc
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_free
1>http_hdr.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_free
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_free
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_free
1>http_tmpl.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_free
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_vstring_strcat，该符号在函数 _http_hdr_entry_replace2 中被引用
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_strcat
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_strcat
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_vstring_strncat，该符号在函数 _http_hdr_entry_replace2 中被引用
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_vstring_sprintf，该符号在函数 _http_hdr_sprint 中被引用
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_sprintf
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_sprintf
1>http_tmpl.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_sprintf
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_vstring_sprintf_append，该符号在函数 _http_hdr_sprint 中被引用
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_sprintf_append
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_sprintf_append
1>http_tmpl.obj : error LNK2001: 无法解析的外部符号 _acl_vstring_sprintf_append
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_fprintf，该符号在函数 _http_hdr_fprint 中被引用
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_fprintf
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_msg_info，该符号在函数 _http_hdr_print 中被引用
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_msg_info
1>icmp_stat.obj : error LNK2001: 无法解析的外部符号 _acl_msg_info
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_malloc_glue，该符号在函数 _http_hdr_entry_build 中被引用
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_malloc_glue
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_strdup_glue，该符号在函数 _http_hdr_entry_new 中被引用
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_strdup_glue
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_free_fn_glue，该符号在函数 _http_hdr_free 中被引用
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_strcasestr，该符号在函数 _http_hdr_entry_replace2 中被引用
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_strcasecmp，该符号在函数 _http_hdr_parse 中被引用
1>http_hdr_build.obj : error LNK2001: 无法解析的外部符号 _acl_strcasecmp
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_strcasecmp
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_strcasecmp
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_strncasecmp，该符号在函数 _http_hdr_parse_version 中被引用
1>http_hdr_req.obj : error LNK2001: 无法解析的外部符号 _acl_strncasecmp
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_strncasecmp
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_strncasecmp
1>http_hdr.obj : error LNK2019: 无法解析的外部符号 _acl_atoui64，该符号在函数 _http_hdr_parse 中被引用
1>http_hdr_build.obj : error LNK2019: 无法解析的外部符号 _acl_vstring_vsprintf_append，该符号在函数 _http_hdr_put_fmt 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_main_thread_self，该符号在函数 _http_hdr_req_new 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_main_thread_self
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_pthread_once，该符号在函数 _http_hdr_req_new 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_pthread_once
1>icmp_chat.obj : error LNK2001: 无法解析的外部符号 _acl_pthread_once
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_pthread_key_create，该符号在函数 _cache_init 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_pthread_key_create
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_pthread_getspecific，该符号在函数 _http_hdr_req_new 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_pthread_getspecific
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_pthread_setspecific，该符号在函数 _http_hdr_req_new 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_pthread_setspecific
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_pthread_self，该符号在函数 _http_hdr_req_new 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_pthread_self
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_pthread_tls_get，该符号在函数 _http_hdr_req_url 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_pthread_tls_set，该符号在函数 _http_hdr_req_url 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_htable_create，该符号在函数 _http_hdr_req_clone 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_htable_enter，该符号在函数 _clone_table_entry 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_htable_find，该符号在函数 _http_hdr_req_cookie_get 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_htable_free，该符号在函数 ___hdr_free_member 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_htable_reset，该符号在函数 ___hdr_reset 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_htable_walk，该符号在函数 _http_hdr_req_clone 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_vbuf_put，该符号在函数 _http_hdr_req_create 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_vstring_strcpy，该符号在函数 _http_hdr_req_create 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_vstring_strncpy，该符号在函数 ___parse_url_and_port 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_vstring_export，该符号在函数 _http_hdr_req_rewrite2 中被引用
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_argv_free，该符号在函数 _http_hdr_req_cookies_parse 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_argv_free
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_argv_free
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_argv_index，该符号在函数 _http_hdr_req_line_parse 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_argv_index
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_argv_split，该符号在函数 _http_hdr_req_cookies_parse 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_argv_split
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_argv_split
1>http_hdr_req.obj : error LNK2019: 无法解析的外部符号 _acl_atoi64，该符号在函数 _http_hdr_req_range 中被引用
1>http_hdr_res.obj : error LNK2001: 无法解析的外部符号 _acl_atoi64
1>http_tmpl.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_fopen，该符号在函数 ___load_tmpl 中被引用
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_fopen
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_fopen
1>http_tmpl.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_close，该符号在函数 ___load_tmpl 中被引用
1>http_util.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_close
1>icmp_stream.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_close
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_close
1>http_util.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_writen，该符号在函数 _http_util_req_open 中被引用
1>icmp_chat_aio.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_writen
1>icmp_chat_sio.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_writen
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_writen
1>http_util.obj : error LNK2019: 无法解析的外部符号 _acl_concatenate，该符号在函数 _http_util_set_req_cookie 中被引用
1>http_util.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_connect，该符号在函数 _http_util_req_open 中被引用
1>smtp_client.obj : error LNK2001: 无法解析的外部符号 _acl_vstream_connect
1>icmp_chat.obj : error LNK2019: 无法解析的外部符号 _acl_ring_init，该符号在函数 _icmp_chat_create 中被引用
1>icmp_chat_aio.obj : error LNK2001: 无法解析的外部符号 _acl_ring_init
1>icmp_timer.obj : error LNK2001: 无法解析的外部符号 _acl_ring_init
1>icmp_chat.obj : error LNK2019: 无法解析的外部符号 _acl_ring_size，该符号在函数 _icmp_chat_size 中被引用
1>icmp_stat.obj : error LNK2001: 无法解析的外部符号 _acl_ring_size
1>icmp_chat.obj : error LNK2019: 无法解析的外部符号 _acl_atomic_new，该符号在函数 _icmp_once 中被引用
1>icmp_chat.obj : error LNK2019: 无法解析的外部符号 _acl_atomic_free，该符号在函数 _proc_on_exit 中被引用
1>icmp_chat.obj : error LNK2019: 无法解析的外部符号 _acl_atomic_set，该符号在函数 _icmp_once 中被引用
1>icmp_chat.obj : error LNK2019: 无法解析的外部符号 _acl_atomic_int64_fetch_add，该符号在函数 _icmp_chat_create 中被引用
1>icmp_chat_aio.obj : error LNK2019: 无法解析的外部符号 _acl_ring_pop_head，该符号在函数 _icmp_rset 中被引用
1>icmp_chat_aio.obj : error LNK2019: 无法解析的外部符号 _acl_aio_set_delay_sec，该符号在函数 _icmp_chat_aio_add 中被引用
1>icmp_chat_aio.obj : error LNK2019: 无法解析的外部符号 _acl_aio_set_delay_usec，该符号在函数 _icmp_chat_aio_add 中被引用
1>icmp_chat_aio.obj : error LNK2019: 无法解析的外部符号 _acl_aio_read，该符号在函数 _icmp_chat_aio_add 中被引用
1>icmp_chat_aio.obj : error LNK2019: 无法解析的外部符号 _acl_aio_request_timer，该符号在函数 _icmp_chat_aio_add 中被引用
1>icmp_chat_sio.obj : error LNK2019: 无法解析的外部符号 _gettimeofday，该符号在函数 _send_pkt 中被引用
1>icmp_stat.obj : error LNK2001: 无法解析的外部符号 _gettimeofday
1>icmp_chat_sio.obj : error LNK2019: 无法解析的外部符号 _acl_read_select_wait，该符号在函数 _read_pkt 中被引用
1>icmp_chat_sio.obj : error LNK2019: 无法解析的外部符号 _acl_doze，该符号在函数 _icmp_chat_sio 中被引用
1>icmp_host.obj : error LNK2019: 无法解析的外部符号 __imp__inet_addr@4，该符号在函数 _icmp_host_alloc 中被引用
1>icmp_host.obj : error LNK2019: 无法解析的外部符号 _acl_ring_prepend，该符号在函数 _icmp_host_alloc 中被引用
1>icmp_timer.obj : error LNK2001: 无法解析的外部符号 _acl_ring_prepend
1>icmp_pkt.obj : error LNK2019: 无法解析的外部符号 __imp__inet_ntoa@4，该符号在函数 _icmp_pkt_unpack 中被引用
1>icmp_stream.obj : error LNK2019: 无法解析的外部符号 __imp__recvfrom@24，该符号在函数 _icmp_read 中被引用
1>icmp_stream.obj : error LNK2019: 无法解析的外部符号 __imp__sendto@24，该符号在函数 _icmp_write 中被引用
1>icmp_stream.obj : error LNK2019: 无法解析的外部符号 __imp__socket@12，该符号在函数 _icmp_stream_open 中被引用
1>icmp_stream.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_fdopen，该符号在函数 _icmp_stream_open 中被引用
1>icmp_stream.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_ctl，该符号在函数 _icmp_stream_open 中被引用
1>icmp_stream.obj : error LNK2019: 无法解析的外部符号 _acl_aio_open，该符号在函数 _icmp_stream_open 中被引用
1>icmp_stream.obj : error LNK2019: 无法解析的外部符号 _acl_aio_iocp_close，该符号在函数 _icmp_stream_close 中被引用
1>icmp_timer.obj : error LNK2019: 无法解析的外部符号 _acl_ring_detach，该符号在函数 _timer_request 中被引用
1>smtp_client.obj : error LNK2019: 无法解析的外部符号 _acl_vstream_vfprintf，该符号在函数 _smtp_printf 中被引用
1>smtp_client.obj : error LNK2019: 无法解析的外部符号 _acl_base64_encode，该符号在函数 _smtp_auth 中被引用
1>.\lib_protocol_vc2015d.dll : fatal error LNK1120: 97 个无法解析的外部命令
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

**Comment by zhengshuxin** [comment]
你在编译acl dll时无需在工程里设置编译成dll方式，只需选择 DebugDll 或 ReleaseDll 即可。

![图片](https://user-images.githubusercontent.com/1060042/100533034-c9333380-323a-11eb-9099-c8502b1d2bff.png)
