### ISSUE TITLE
当redis主机挂掉的时候, 这时候mset, 程序crash了. 

### ISSUE THREAD

**Issue by solowolf** [acl-dev/acl#230]
acl::acl_cpp_init();

	ostringstream oss_addr;
	oss_addr << redis_ip << ":" << redis_port;
	string addr = string(redis_ip) + string(":") + boost::lexical_cast<string>(redis_port);
	string addr2 = oss_addr.str();
	this->redis_cli = new acl::redis_client(addr.c_str());
	this->redis_cli->set_password(passwd.c_str());
	this->redis_str.set_client(this->redis_cli);
	this->redis_keys.set_client(this->redis_cli);

bool retval = redis_comm_fast->mset(map_kv);  <=== 挂了

**Comment by zhengshuxin** [comment]
有崩溃的栈信息吗？最好把崩溃行给一下。

**Comment by solowolf** [comment]
时间是去年了, redis云主机挂了, 导致的崩溃.  后续版本我会继续跟踪
