### ISSUE TITLE
Windows下使用acl_redis模块连接会失败！

### ISSUE THREAD

**Issue by liangrf** [acl-dev/acl#233]
Win 10环境下，使用acl_redis连接本机的Redis6.0会失败，跟踪代码发现是acl_read_poll_wait方法里的WSAPoll方法返回失败，经过尝试，将fds.events = POLLIN | POLLHUP | POLLERR改成fds.events = POLLIN后，可以正常连接使用。

**Comment by zhengshuxin** [comment]
问题已修复，谢谢提醒。又查看了一下官方文档（https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsapoll ），在Windows 下 WSAPoll 与 UNIX 下的 poll 使用确实有所不同，Windows 下  POLLHUP | POLLERR 不能设置在请求参数中，只会在结果中返回。
