### ISSUE TITLE
中文括号，从数据库中读取从utf8转GBK出现错误

### ISSUE THREAD

**Issue by SunLiangcan** [acl-dev/acl#234]
数据存存储在mysql中，格式为utf8。
从数据中读取数据，utf8转GBK出现乱码，原文字为中文左括号"（"转换后为"紙"
下图为转换前
![image](https://user-images.githubusercontent.com/21167894/109442934-52dde180-7a74-11eb-9b86-529a5bb3222c.png)
下图为转换后，代码和结果都在图里
![image](https://user-images.githubusercontent.com/21167894/109443104-aa7c4d00-7a74-11eb-8f6d-78b846292b43.png)

自己写的转换正常
![image](https://user-images.githubusercontent.com/21167894/109443027-7f91f900-7a74-11eb-9ca3-a48195462b1a.png)

**Comment by zhengshuxin** [comment]
能否确定是存储于 mysql 有问题还是字符集转码有问题？

**Comment by SunLiangcan** [comment]
是字符集的问题，同样的内容，使用自己封装的win下的api转换没有问题

**Comment by SunLiangcan** [comment]
![image](https://user-images.githubusercontent.com/21167894/109602445-0f11d780-7b5b-11eb-806c-a1c1166575b2.png)
**

下面是用win下api写的ConvertUtf8ToGB2312实现

**
![image](https://user-images.githubusercontent.com/21167894/109602444-0f11d780-7b5b-11eb-9d67-7d6a1bf02ffc.png)

**Comment by SunLiangcan** [comment]
乱码开头
![image](https://user-images.githubusercontent.com/21167894/109609247-0a065580-7b66-11eb-92fb-8fbb03ac1e8a.png)


**我修改了charset_conv.cpp文件228行，改m_pUtf8Pre = UTF8_HEADER; 为m_pUtf8Pre = &UTF8_HEADER[3];，转换就正常了**

![image](https://user-images.githubusercontent.com/21167894/109609990-1a6b0000-7b67-11eb-9afc-26acb0fe4531.png)
正常截图
![image](https://user-images.githubusercontent.com/21167894/109610160-569e6080-7b67-11eb-8ced-e828bcd0d08f.png)

**Comment by SunLiangcan** [comment]
这是避免文档中的开头？

**Comment by zhengshuxin** [comment]
原意是为了避开前面的BOM引导头。
