### ISSUE TITLE
acl_readable对正常的空闲连接检测有100ms的等待

### ISSUE THREAD

**Issue by nijiancong** [acl-dev/acl#237]
文件位置：acl/lib_acl/src/stdlib/iostuff/acl_readable.c
函数名称：int acl_readable(ACL_SOCKET fd)
该函数对异常连接检测可以立即返回，
但是对正常连接检测100ms后才会返回。
猜测是因为对fd注册只读事件后，
正常的空闲连接poll并没有可读事件立即响应，
等待了一个超时时间才响应的

**Comment by zhengshuxin** [comment]
你是在哪个操作系统平台上测试的？可以参考一下具体实现：https://github.com/acl-dev/acl/blob/master/lib_acl/src/stdlib/iostuff/acl_readable.c

**Comment by nijiancong** [comment]
测试环境Ubuntu 18.04.5 LTS x86_64
经过进一步的测试验证，只有在使用fiber时调用acl_readable()才会有100ms的等待
测试方法，使用acl现有的例子
1. 不使用fiber
测试例子：acl/lib_acl_cpp/samples/socket/client/main.cpp
测试方法：在例子中client.alive()调用前后打印时间
测试说明：client.alive()会调用acl_readable()
测试结果：client.alive()没有延迟
2. 使用fiber
测试例子：acl/lib_fiber/samples/client/main.c
测试方法：在连接建立后加一行检测 acl_socket_alive(ACL_VSTREAM_SOCK(cstream));并打印调用时间
测试说明: 没找到现成的例子，所以这里加行代码，acl_socket_alive()会调用acl_readable()
测试结果：acl_socket_alive() 有100ms+的延迟

**Comment by zhengshuxin** [comment]
> 测试环境Ubuntu 18.04.5 LTS x86_64
> 经过进一步的测试验证，只有在使用fiber时调用acl_readable()才会有100ms的等待
> 测试方法，使用acl现有的例子
> 
>     1. 不使用fiber
>        测试例子：acl/lib_acl_cpp/samples/socket/client/main.cpp
>        测试方法：在例子中client.alive()调用前后打印时间
>        测试说明：client.alive()会调用acl_readable()
>        测试结果：client.alive()没有延迟
> 
>     2. 使用fiber
>        测试例子：acl/lib_fiber/samples/client/main.c
>        测试方法：在连接建立后加一行检测 acl_socket_alive(ACL_VSTREAM_SOCK(cstream));并打印调用时间
>        测试说明: 没找到现成的例子，所以这里加行代码，acl_socket_alive()会调用acl_readable()
>        测试结果：acl_socket_alive() 有100ms+的延迟

谢谢提醒，问题已修复，所修改的文件：acl/lib_fiber/c/src/event.c, acl/lib_fiber/c/src/hook/poll.c, 
参考示例：acl/lib_fiber/samples-c++1x/server。

**Comment by nijiancong** [comment]
测试ok
