### ISSUE TITLE
window10 64位，lib库  连接redis 消息订阅 内存异常

### ISSUE THREAD

**Issue by liyaogis** [acl-dev/acl#239]
acl::acl_cpp_init();

	acl::redis_client  client( addr.c_str(), conn_timeout, rw_timeout);

	acl::redis_pubsub redis(&client);

       redis.subscribe(“1”);   // 内存异常
![image](https://user-images.githubusercontent.com/13028162/121613384-e5881680-ca8e-11eb-975a-08d1f97888b3.png)

**Comment by zhengshuxin** [comment]
int subscribe(const char* first_channel, ...); 是一个变参方法，最后一个参数必须以 NULL 结尾。
