### ISSUE TITLE
acl redis hmset超过60万会写入错误？

### ISSUE THREAD

**Issue by threeman123** [acl-dev/acl#240]
用hmset函数写入一个超过60万对的map，返回错误，请问有限制吗

**Comment by zhengshuxin** [comment]
有可能是 redis 服务 端的限制，不过不应一次性通过 hmset 写入这么大量的数据，你可以分批次写入试试。

**Comment by threeman123** [comment]
分批写入是没有问题的，请问您是否知道redis服务配置中有此方面的限制吗

**Comment by threeman123** [comment]
或者说，您是否有推荐分批写入的数量，比如每10万条写入一次？

**Comment by zhengshuxin** [comment]
这得看redis源码了，一般很少有应用一次性写入这么多数据。

**Comment by zhengshuxin** [comment]
这得看redis源码了，一般很少有应用一次性写入这么多数据。

**Comment by threeman123** [comment]
谢谢
