### ISSUE TITLE
acl redis字符串编码问题

### ISSUE THREAD

**Issue by threeman123** [acl-dev/acl#242]
您好，acl redis接口使用过程中遇到一些编码问题：
1. 用utf8编码char*构造的acl:string写入redis会出现key有乱码
2. 改用Latin1写入后问题解决，但hget的field用Latin1取不到数据，实际是有的
3. 改用local8bit问题解决
请问，redis编码是跟写入的char*编码有关还是接口做了什么处理？

**Comment by threeman123** [comment]
另，redis目前的存值都是英文和字符，没有中文

**Comment by zhengshuxin** [comment]
redis 支持存储二进制，是不区分字符集编码的，acl redis 库也是支持二进制的，字符集转换由应用层自己进行。
