### ISSUE TITLE
We need to use only https calls to communicate with redis. Can we use openssl or we need to use only polarssl?

### ISSUE THREAD

**Issue by muralipithani** [acl-dev/acl#245]
Can we use openssl or we need to use only polarssl? If only polarssl, why cant we use openssl?
 
 Though I have above queries, I tried to use polarssl in the redis_ssl sample in linux machine and though the build was fine, I am getting error while connecting even after the the polarssl libs are loaded.

below is the error 

polarssl_io.cpp(447), handshake: ssl_handshake failed: -0x004c
redis_client.cpp(121), open: open ssl failed, addr=127.0.0.1:6379

**Comment by zhengshuxin** [comment]
Only polarssl and mbedtls can be supported in acl, openssl and other ssl libs maybe be supported in the future. The special version of polarssl and mbedtls used by acl can be found in https://github.com/acl-dev/third_party .

**Comment by muralipithani** [comment]
Thankyou.. I've been trying to run the example in the redis_ssl where I was facing handshake issue using the polarssl from above third party path in CentOS
Machine. Any suggestions or solutions on this?

Other doubt being that, is there a specific redis version that needs to be used to use the SSL communication with redis server?

**Comment by muralipithani** [comment]
Can we get the steps to build polarssl in windows.. it would be of great help

**Comment by zhengshuxin** [comment]
Please refer the shell t.sh in redis_ssl, the SSL's cert and key should be provided. Below is the usage:
./redis -s 127.0.0.1:6379 -L ../libpolarssl.dylib  -c -C ca.crt -S redis.crt -K redis.key

**Comment by muralipithani** [comment]
Yes.. it worked with the above information. But the same when trying to implement in windows, polarssl DLL load is returning 127 error code by the GetProcAddress() 

Could you help with any solution for the same?

**Comment by zhengshuxin** [comment]
That is because the APIs of polarssl were not be exported in the original vc project provided by polarssl lib. 
I've just added vs2019 project for mbedtls in https://github.com/acl-dev/third_party/tree/master/mbedtls-2.7.12/visualc/VC2019, and you can try to use it to get mbedtls.dll to be used in redis_ssl sample, where I've also add vc2019 project to compile redis_ssl on Windows. After you've built mbedtls.dll and redis_ssl, then you can run redis_ssl as below:

.\Debug\redis_ssl.exe -s  xxx.xxx.xxx.xxx:6379 -L.\mbedtls.dll -c -C ca.crt -S redis.crt -K redis.key -a set -n 100 .

The ca.crt, redis.crt and redis.key were genterated by `./utils/gen-test-certs.sh` in redis, more info can be found in TLS.md in redis. And I ran redis as below:

./src/redis-server --tls-port 6379 --port 0 \
        --tls-cert-file ./tests/tls/redis.crt \
        --tls-key-file ./tests/tls/redis.key \
        --tls-ca-cert-file ./tests/tls/ca.crt \
        --protected-mode no

I've tested it successfully. 
--zsx

**Comment by muralipithani** [comment]
Thank you.. Main concern is that, do we have to always pass the cert, key files? Considering that how to use in a bigger project rather compared to the samples any suggestions that you could suggest?

**Comment by zhengshuxin** [comment]
Yes, the cer, key files should be passed to redis server which is needed by redis-server, TLS.md in redis source can be refered.
The acl project has been used by many big companies in China for years with high performance and stability, which are servicing billion peoples in China. I've written many blogs in https://blog.csdn.net/zsxxsz/ to introduce how to use acl in your projects, but which were wrote in Chinese.
I've also written many simple demos in https://github.com/acl-dev/demo for user to undstand and use acl. If you want to write a server, the wizard in https://github.com/acl-dev/acl/tree/master/app/wizard can be used to generate some kinds of server projects very easily.

**Comment by muralipithani** [comment]
Currently we are trying to include the acl libraries using the static library files(.a files). Linking in them in the same sequence of the way we built them lib_acl, lib_protocol and lib_acl_cpp but getting the below error.

 undefined reference to `acl_vstring_free'
undefined reference to `acl_vstring_alloc'
undefined reference to `acl_vstring_memcpy'
undefined reference to `acl_vstring_memcpy'

These error are seen for many such methods.. could you let us know solution for this?

**Comment by zhengshuxin** [comment]
BUILD.md can be refered for building acl libs into your projects, which was written by Chinese, you can use google's translate to translate it to English. Also, FAQ.md can be refered to find the common problems when using acl libs.

**Comment by muralipithani** [comment]
We already use ssl library in our project. there would be any conflict between existing ssl and the polarssl? Please let me know

**Comment by zhengshuxin** [comment]
> We already use ssl library in our project. there would be any conflict between existing ssl and the polarssl? Please let me know
There'll be no confilct between the existing ssl and polarssl/mbedtls used by acl, because acl will load the so or dll of polarssl in dynamic way.

**Comment by muralipithani** [comment]
When we included the acl libraries and tried to build, it was fine in windows but in linux(Centos) we were getting "**undefined reference**" error. After adding the -ldl flag, build was successful. When starting our application we load the LD_LIBRARY and when started, we were getting "HASH_MATCH","The provided hash-based authentication code is invalid"

> > We already use ssl library in our project. there would be any conflict between existing ssl and the polarssl? Please let me know
> > There'll be no confilct between the existing ssl and polarssl/mbedtls used by acl, because acl will load the so or dll of polarssl in dynamic way.

**Comment by zhengshuxin** [comment]
Did you try one sample of acl? And please give me some  detailed information for me to analyse it.

**Comment by muralipithani** [comment]
> Did you try one sample of acl? And please give me some detailed information for me to analyse it.

Yes.. I tried the sample in both linux and windows.. I was able to run the sample in Linux successfully but in windows, while loading the polarssl dll I am facing error. As I am trying to emphasize more on linux I started and included acl libs. Build was successful and when starting our application, I am getting connectivity issues with redis server which I started in TLS mode. 

I made necessary changes to refer to the key files and also polarssl.so file from a specific path in 1 machine where we have our application. I have redis server running in TLS mode in another machine. When we are trying to connect to the redis through our application below error on redis client is observed.

84667:M 13 Jul 2021 15:47:54.908 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
84667:M 13 Jul 2021 15:47:54.909 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
84667:M 13 Jul 2021 15:47:54.911 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
84667:M 13 Jul 2021 15:47:54.912 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
84667:M 13 Jul 2021 15:47:54.915 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
84667:M 13 Jul 2021 15:47:54.916 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding


Could you please help with this error?

**Comment by muralipithani** [comment]
> > Did you try one sample of acl? And please give me some detailed information for me to analyse it.
> 
> Yes.. I tried the sample in both linux and windows.. I was able to run the sample in Linux successfully but in windows, while loading the polarssl dll I am facing error. As I am trying to emphasize more on linux I started and included acl libs. Build was successful and when starting our application, I am getting connectivity issues with redis server which I started in TLS mode.
> 
> I made necessary changes to refer to the key files and also polarssl.so file from a specific path in 1 machine where we have our application. I have redis server running in TLS mode in another machine. When we are trying to connect to the redis through our application below error on redis client is observed.
> 
> 84667:M 13 Jul 2021 15:47:54.908 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
> 84667:M 13 Jul 2021 15:47:54.909 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
> 84667:M 13 Jul 2021 15:47:54.911 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
> 84667:M 13 Jul 2021 15:47:54.912 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
> 84667:M 13 Jul 2021 15:47:54.915 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
> 84667:M 13 Jul 2021 15:47:54.916 # Error accepting a client connection: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
> 
> Could you please help with this error?

I found that we should not use the certificate key files after copying to another folder or machine. When I generated in 1 machine and tried to connect with redis, I worked. But the main intension behind this inclusion of redis cache is that we wanted to have common redis across 2 or more machines connected to redis. In that case, how do we connect to redis with the same keys?

**Comment by zhengshuxin** [comment]
In my test, the cert key files must be generated in one machine, which are used in redis server and client, or some error will happen in SSL handshaking. This because the redis client should use CA to check the server side's cert, which is like the desktop browser.

**Comment by muralipithani** [comment]
> In my test, the cert key files must be generated in one machine, which are used in redis server and client, or some error will happen in SSL handshaking. This because the redis client should use CA to check the server side's cert, which is like the desktop browser.

What if we want to communicate with redis server from 2 different client machine? What would be the steps to be implemented in that case?

**Comment by zhengshuxin** [comment]
> > In my test, the cert key files must be generated in one machine, which are used in redis server and client, or some error will happen in SSL handshaking. This because the redis client should use CA to check the server side's cert, which is like the desktop browser.
> 
> What if we want to communicate with redis server from 2 different client machine? What would be the steps to be implemented in that case?

I mean that different clients should use the same CA and cert which was generated by gen-test-certs.sh in one machine.

**Comment by MP185388** [comment]
> 
> 
> > > In my test, the cert key files must be generated in one machine, which are used in redis server and client, or some error will happen in SSL handshaking. This because the redis client should use CA to check the server side's cert, which is like the desktop browser.
> > 
> > 
> > What if we want to communicate with redis server from 2 different client machine? What would be the steps to be implemented in that case?
> 
> I mean that different clients should use the same CA and cert which was generated by gen-test-certs.sh in one machine.

I ran the shell script in machine 1 where I have redis also installed along with my application and was able to communicate with the redis. As my requirement is to communicate with the redis server from more than 1client, I copied all the files generated by the shell script on machine 1  to another machine 2. When trying to communicate from the machien2 to redis on machine1 I am getting the above error.

Though my ideal actual requirement is to install redis on machine3 and perform transactions from machine1 and machine2, just for instance I installed redis in the machine1 itself and trying to communicate from machine1 and machine2.

**Comment by muralipithani** [comment]
> > > In my test, the cert key files must be generated in one machine, which are used in redis server and client, or some error will happen in SSL handshaking. This because the redis client should use CA to check the server side's cert, which is like the desktop browser.
> > 
> > 
> > What if we want to communicate with redis server from 2 different client machine? What would be the steps to be implemented in that case?
> 
> I mean that different clients should use the same CA and cert which was generated by gen-test-certs.sh in one machine.

I ran the shell script in machine 1 where I have redis also installed along with my application and was able to communicate with the redis. As my requirement is to communicate with the redis server from more than 1client, I copied all the files generated by the shell script on machine 1 to another machine 2. When trying to communicate from the machien2 to redis on machine1 I am getting the above error.

Though my ideal actual requirement is to install redis on machine3 and perform transactions from machine1 and machine2, just for instance I installed redis in the machine1 itself and trying to communicate from machine1 and machine2.

**Comment by zhengshuxin** [comment]
> > > > In my test, the cert key files must be generated in one machine, which are used in redis server and client, or some error will happen in SSL handshaking. This because the redis client should use CA to check the server side's cert, which is like the desktop browser.
> > > 
> > > 
> > > What if we want to communicate with redis server from 2 different client machine? What would be the steps to be implemented in that case?
> > 
> > 
> > I mean that different clients should use the same CA and cert which was generated by gen-test-certs.sh in one machine.
> 
> I ran the shell script in machine 1 where I have redis also installed along with my application and was able to communicate with the redis. As my requirement is to communicate with the redis server from more than 1client, I copied all the files generated by the shell script on machine 1 to another machine 2. When trying to communicate from the machien2 to redis on machine1 I am getting the above error.
> 
> Though my ideal actual requirement is to install redis on machine3 and perform transactions from machine1 and machine2, just for instance I installed redis in the machine1 itself and trying to communicate from machine1 and machine2.

There is some limit by redis from another machine to access in SSL mode. Dit you start redis with params "--protected-mode no" ? Such as below:
./src/redis-server --tls-port 6379 --port 0 \
        --tls-cert-file ./tests/tls/redis.crt \
        --tls-key-file ./tests/tls/redis.key \
        --tls-ca-cert-file ./tests/tls/ca.crt \
        --protected-mode no
