### ISSUE TITLE
[BUG] Missing lock releases on the lock cond?

### ISSUE THREAD

**Issue by ryancaicse** [acl-dev/acl#250]
Hi, developers, there is a missing lock release of the lock _cond_ when breaking the loop?
https://github.com/acl-dev/acl/blob/6279631074935916d8e5f039635470778162755c/lib_fiber/c/src/fiber_cond.c#L150-L155

**Comment by ryancaicse** [comment]
Similarly, the lock `queue->lock` is not released when `aqueue_wait(queue, ptimeo) < 0`

https://github.com/acl-dev/acl/blob/0c01da318de050819b7bd7f2f09e79098612fc11/lib_acl/src/msg/acl_aqueue.c#L198-L221

**Comment by zhengshuxin** [comment]
> Hi, developers, there is a missing lock release of the lock _cond_ when breaking the loop?
> 
> https://github.com/acl-dev/acl/blob/6279631074935916d8e5f039635470778162755c/lib_fiber/c/src/fiber_cond.c#L150-L155

The lock will be released at line 165 or 180 after break loop.

**Comment by zhengshuxin** [comment]
> Similarly, the lock `queue->lock` is not released when `aqueue_wait(queue, ptimeo) < 0`
> 
> https://github.com/acl-dev/acl/blob/0c01da318de050819b7bd7f2f09e79098612fc11/lib_acl/src/msg/acl_aqueue.c#L198-L221

The lock has been released in aqueue_wait() when it return -1.

**Comment by ryancaicse** [comment]
@zhengshuxin Thank for your reply
