### ISSUE TITLE
如何在一个程序中，同时开启多种协议服务？

### ISSUE THREAD

**Issue by okman334** [acl-dev/acl#251]
如果使用acl开发，在同一个程序中，如果想同时有http, websocket, 普通的tcpserver, 是不是应该在不同的线程中去启动httpserver, websocket, tcpserver呢？谢谢

**Comment by zhengshuxin** [comment]
可以先使用 app/wizard 下的服务生成向导生成 http 服务器程序，在生成的 http_servlet.cpp 中同时支持 http和websocket，另外，可以修改 master_service.cpp 文件，在 thread_on_accept(acl::socket_stream* conn) 中调用 conn->get_local(true)，获得完整的本地监听地址，根据监听地址 的不同来创建 http_servlet 对象或 tcp server 对象即可。

**Comment by okman334** [comment]
> 可以先使用 app/wizard 下的服务生成向导生成 http 服务器程序，在生成的 http_servlet.cpp 中同时支持 http和websocket，另外，可以修改 master_service.cpp 文件，在 thread_on_accept(acl::socket_stream* conn) 中调用 conn->get_local(true)，获得完整的本地监听地址，根据监听地址 的不同来创建 http_servlet 对象或 tcp server 对象即可。

好的，我来试试看看

**Comment by okman334** [comment]
> http

用app/wizard生成的 http_servlet类中，好像有两个虚函数名字写错了。
       // @override  
	bool doProfind(HttpRequest& req, HttpResponse& res);    //应该是doPropfind
	// @override
	bool doWebsocket(HttpRequest& req, HttpResponse& res); //应该是doWebSocket

**Comment by zhengshuxin** [comment]
> > http
> 
> 用app/wizard生成的 http_servlet类中，好像有两个虚函数名字写错了。 // @OverRide bool doProfind(HttpRequest& req, HttpResponse& res); //应该是doPropfind // @OverRide bool doWebsocket(HttpRequest& req, HttpResponse& res); //应该是doWebSocket

是的，这两个方法名字写错了，已修复，谢谢：）

**Comment by okman334** [comment]
> > > http
> 
> > 
> 
> > 用app/wizard生成的 http_servlet类中，好像有两个虚函数名字写错了。 // @OverRide bool doProfind(HttpRequest& req, HttpResponse& res); //应该是doPropfind // @OverRide bool doWebsocket(HttpRequest& req, HttpResponse& res); //应该是doWebSocket
> 
> 
> 
> 是的，这两个方法名字写错了，已修复，谢谢：）

请问在master_aio_server或master_threads框架下，当有数据来了，read了数据，把数据post到另外一个线程A处理，然后处理完后在线程A write 往客户端写数据，这样可以的吗？ 就是io里面的read和write是线程安全的么？

**Comment by zhengshuxin** [comment]
同一个 io 对象的 read/write 不是线程安全的，所以应在同一线程中进行处理。

**Comment by okman334** [comment]
好的。那在多线程模式下，同一个io对象，每次onread回调，应该都是同一条线程回调。某个io对象，在关闭链接前，都是工作在同一条线程上。我的理解应该是对的吧？对于计算密集型的项目，一般数据处理，习惯会放到另外一个线程处理，和io线程分开。

**Comment by zhengshuxin** [comment]
每次回调 thread_on_accpet, thread_on_accept, thread_on_close 时都可能是在不同的线程中，前缀 thread_ 的含义也正是如此。

**Comment by okman334** [comment]
> 可以先使用 app/wizard 下的服务生成向导生成 http 服务器程序，在生成的 http_servlet.cpp 中同时支持 http和websocket，另外，可以修改 master_service.cpp 文件，在 thread_on_accept(acl::socket_stream* conn) 中调用 conn->get_local(true)，获得完整的本地监听地址，根据监听地址 的不同来创建 http_servlet 对象或 tcp server 对象即可。

按照这个逻辑，我觉得在aio server里面的bool accept_callback(acl::aio_socket_stream* client)创建一个class http_servlet : public acl::HttpServlet对象来服务http或者websocket应该也是可以的吧？不过可能性能差点？😂

**Comment by okman334** [comment]
作者大神，你好。又是我，我又来了。

**Comment by okman334** [comment]
作者大神，你好。又是我，我又来了。
初见acl，乍为惊喜的，又见acl，略感忧虑，再见acl，有点怀疑自己。acl框架真的太大了😭，里面啥都有。我用 app/wizard 下生成的框架写了个http服务。但又不太敢线上用，怕有什么东西自己没有处理好。比如我看线程数设置得特别大（我看生成的cf文件配置的是250条线程）。当线程数大于CPU核心数目的时候，更多的线程是否还能提高性能呢？假设thread_on_read的时候，可能需要通过httpclient访问第三方的数据，这个时候，可能线程被阻塞在这里了。

**Comment by zhengshuxin** [comment]
> thread_on_read



> 作者大神，你好。又是我，我又来了。 初见acl，乍为惊喜的，又见acl，略感忧虑，再见acl，有点怀疑自己。acl框架真的太大了😭，里面啥都有。我用 app/wizard 下生成的框架写了个http服务。但又不太敢线上用，怕有什么东西自己没有处理好。比如我看线程数设置得特别大（我看生成的cf文件配置的是250条线程）。当线程数大于CPU核心数目的时候，更多的线程是否还能提高性能呢？假设thread_on_read的时候，可能需要通过httpclient访问第三方的数据，这个时候，可能线程被阻塞在这里了。

你用wizard所生成的线程池HTTP服务内部是线程池与事件结合方式，当空闲连接较多时，这些空闲连接并不会占用线程，只有当连接读数据并需要处理时才会占用一个线程，如果该线程访问第三方数据确实可能会产生阻塞，至于线程数量设置成250也只是一个经验值（在4核以上设成250应该不会有问题的）；当然，如果你想要支持更多的并发并且希望性能更高，可以使用 wizard 生成基于协程方式的HTTP服务程序。

**Comment by zhengshuxin** [comment]
> > 可以先使用 app/wizard 下的服务生成向导生成 http 服务器程序，在生成的 http_servlet.cpp 中同时支持 http和websocket，另外，可以修改 master_service.cpp 文件，在 thread_on_accept(acl::socket_stream* conn) 中调用 conn->get_local(true)，获得完整的本地监听地址，根据监听地址 的不同来创建 http_servlet 对象或 tcp server 对象即可。
> 
> 按照这个逻辑，我觉得在aio server里面的bool accept_callback(acl::aio_socket_stream* client)创建一个class http_servlet : public acl::HttpServlet对象来服务http或者websocket应该也是可以的吧？不过可能性能差点？😂

aio server 里不能直接在非阻塞线程里使用 http_servlet 类，因为该类的设计是阻塞的，会阻塞非阻塞线程；可以采用协程服务方式，http_servlet 类在协程里是没有问题的。
