### ISSUE TITLE
acl redis dll 隱式呼叫 memory leak

### ISSUE THREAD

**Issue by KuoSherman** [acl-dev/acl#254]
編譯環境: Visual Studio 2008
編譯參數: Debug Mode編譯Acl Redis Dll (3.5.3-0)

測試環境: Visual Studio 2008
新建專案，利用VC將dll載入(隱式呼叫)，建立Redis Client連線，程式結束後檢測到memory leak
測試參數:
1.屬性->C/C++->其他Include目錄: acl\include, acl_protocol\include, acl_cpp\include
2.屬性->連結器->一般->其他程式庫目錄: acl\lib, acl_protocol\lib, acl_cpp\lib
3.屬性->輸入->其他相依性:lib_acl_cpp_d.lib, lib_acl_d.lib, lib_protocol_d.lib

測試Code如下:
#define _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h>
#define DBG_NEW new ( _NORMAL_BLOCK , __FILE__ , __LINE__ )

#include "iostream"
#include "acl_cpp/lib_acl.hpp"

int main()
{
    acl::redis_client connnn("127.0.0.1", 60, 60);
    connnn.close();

    _CrtDumpMemoryLeaks();

    system("PAUSE");
    return 0;
}

檢測結果:

Detected memory leaks!
Dumping objects ->
{149} normal block at 0x00DD64C8, 18 bytes long.
 Data: <        127.0.0.> AD DE 00 00 0A 00 00 00 31 32 37 2E 30 2E 30 2E 
{147} normal block at 0x00DD63A8, 72 bytes long.
 Data: <    @           > AD DE 00 00 40 00 00 00 00 CD CD CD CD CD CD CD 
{146} normal block at 0x00DD6330, 60 bytes long.
 Data: <    4    c   c  > AD DE 00 00 34 00 00 00 B0 63 DD 00 B0 63 DD 00 
{145} normal block at 0x00DD62A8, 72 bytes long.
 Data: <    @           > AD DE 00 00 40 00 00 00 00 CD CD CD CD CD CD CD 
{144} normal block at 0x00DD6230, 60 bytes long.
 Data: <    4    b   b  > AD DE 00 00 34 00 00 00 B0 62 DD 00 B0 62 DD 00 
{143} normal block at 0x00DD61E8, 12 bytes long.
 Data: < a   a      > E8 61 DD 00 E8 61 DD 00 CD CD CD CD 
{142} normal block at 0x00DD2B68, 12 bytes long.
 Data: <h+  h+      > 68 2B DD 00 68 2B DD 00 CD CD CD CD 
{141} normal block at 0x00DD6160, 72 bytes long.
 Data: <    @           > AD DE 00 00 40 00 00 00 00 CD CD CD CD CD CD CD 
{140} normal block at 0x00DD60E8, 60 bytes long.
 Data: <    4   ha  ha  > AD DE 00 00 34 00 00 00 68 61 DD 00 68 61 DD 00 
{139} normal block at 0x00DD6060, 72 bytes long.
 Data: <    @           > AD DE 00 00 40 00 00 00 00 CD CD CD CD CD CD CD 
{138} normal block at 0x00DD5FE8, 60 bytes long.
 Data: <    4   h`  h`  > AD DE 00 00 34 00 00 00 68 60 DD 00 68 60 DD 00 
{137} normal block at 0x00DD2AE0, 72 bytes long.
 Data: <    @           > AD DE 00 00 40 00 00 00 00 CD CD CD CD CD CD CD 
{136} normal block at 0x00DD2A68, 60 bytes long.
 Data: <    4    *   *  > AD DE 00 00 34 00 00 00 E8 2A DD 00 E8 2A DD 00 
{135} normal block at 0x00DD29E0, 72 bytes long.
 Data: <    @           > AD DE 00 00 40 00 00 00 00 CD CD CD CD CD CD CD 
{134} normal block at 0x00DD2968, 60 bytes long.
 Data: <    4    )   )  > AD DE 00 00 34 00 00 00 E8 29 DD 00 E8 29 DD 00 
{133} normal block at 0x00DD28E0, 72 bytes long.
 Data: <    @           > AD DE 00 00 40 00 00 00 00 CD CD CD CD CD CD CD 
{132} normal block at 0x00DD2868, 60 bytes long.
 Data: <    4    (   (  > AD DE 00 00 34 00 00 00 E8 28 DD 00 E8 28 DD 00 
Object dump complete.

請問一下，有人知道問題在哪嗎?

**Comment by KuoSherman** [comment]
有人遇到相同状况吗?

目前测试使用Pool也会有相同状况

**Comment by zhengshuxin** [comment]
其中没有给出具体的行号，这有可能是vc的内存检测工具的问题，我在Linux下用 valgrind 检查是OK的。

**Comment by KuoSherman** [comment]
感谢 zhengshuxin 回复
我使用VLD( https://github.com/KindDragon/vld ) 重新检测过后并没有Memory Leak
推测可能真的是Vc2008检测工具问题
