### ISSUE TITLE
SQLite查询数据库时，如果text类型的项为空，会直接导致异常

### ISSUE THREAD

**Issue by liangrf** [acl-dev/acl#255]

**Comment by zhengshuxin** [comment]
麻烦提供一下测试用例。

**Comment by liangrf** [comment]
> 麻烦提供一下测试用例。

sqlite新建一个表，表中一项为Text类型，插入数据时不给这项插入，查询时就会出现。

**Comment by zhengshuxin** [comment]
问题应该修复了，针对建表时未指定缺省值时插入数据的异常（不给该项加数据），内部增加了判空机制以防止异常。
