### ISSUE TITLE
Issue while compiling on Alpine linux docker container.

### ISSUE THREAD

**Issue by Muralikrishnapithani** [acl-dev/acl#261]
Initially while generating the libs on Alpine, I got below error 

![image](https://user-images.githubusercontent.com/86776086/149744347-92dad487-d4e9-4cd4-a41c-72691b3b3fcc.png)

Tried to change it to PTHREAD_MUTEX_RECURSIVE and compilation went ahead but again got below issues.

In file included from src/stdlib/iostuff/acl_read_wait.c:13:
/usr/include/sys/poll.h:1:2: error: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Werror=cpp]
    1 | #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
      |  ^~~~~~~
src/stdlib/iostuff/acl_read_wait.c: In function 'main_epoll_end':
src/stdlib/iostuff/acl_read_wait.c:45:56: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'acl_pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
   45 |   acl_msg_info("%s(%d), %s: close epoll_fd: %d, tid: %lu, %lu",
      |                                                      ~~^
      |                                                        |
      |                                                        long unsigned int
   46 |    __FILE__, __LINE__, myname, main_epoll_ctx->epfd,
   47 |    main_epoll_ctx->tid, acl_pthread_self());
      |    ~~~~~~~~~~~~~~~~~~~
      |                  |
      |                  acl_pthread_t {aka struct __pthread *}
src/stdlib/iostuff/acl_read_wait.c:45:61: error: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
   45 |   acl_msg_info("%s(%d), %s: close epoll_fd: %d, tid: %lu, %lu",
      |                                                           ~~^
      |                                                             |
      |                                                             long unsigned int
src/stdlib/iostuff/acl_read_wait.c: In function 'thread_epoll_end':
src/stdlib/iostuff/acl_read_wait.c:64:55: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'acl_pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
   64 |  acl_msg_info("%s(%d), %s: close epoll_fd: %d, tid: %lu, %lu",
      |                                                     ~~^
      |                                                       |
      |                                                       long unsigned int
   65 |   __FILE__, __LINE__, myname, epoll_ctx->epfd,
   66 |   epoll_ctx->tid, acl_pthread_self());
      |   ~~~~~~~~~~~~~~
      |            |
      |            acl_pthread_t {aka struct __pthread *}
src/stdlib/iostuff/acl_read_wait.c:64:60: error: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
   64 |  acl_msg_info("%s(%d), %s: close epoll_fd: %d, tid: %lu, %lu",
      |                                                          ~~^
      |                                                            |
      |                                                            long unsigned int
src/stdlib/iostuff/acl_read_wait.c: In function 'thread_epoll_init':
src/stdlib/iostuff/acl_read_wait.c:95:6: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
   95 |  if ((unsigned int) acl_pthread_self() == acl_main_thread_self()) {
      |      ^
src/stdlib/iostuff/acl_read_wait.c:100:57: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'acl_pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  100 |   acl_msg_info("%s(%d): %s, create epoll_fd: %d, tid: %lu, %lu",
      |                                                       ~~^
      |                                                         |
      |                                                         long unsigned int
  101 |    __FILE__, __LINE__, myname, epoll_ctx->epfd,
  102 |    epoll_ctx->tid, acl_pthread_self());
      |    ~~~~~~~~~~~~~~
      |             |
      |             acl_pthread_t {aka struct __pthread *}
src/stdlib/iostuff/acl_read_wait.c:100:62: error: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  100 |   acl_msg_info("%s(%d): %s, create epoll_fd: %d, tid: %lu, %lu",
      |                                                            ~~^
      |                                                              |
      |                                                              long unsigned int
src/stdlib/iostuff/acl_read_wait.c:104:57: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'acl_pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  104 |   acl_msg_info("%s(%d): %s, create epoll_fd: %d, tid: %lu, %lu",
      |                                                       ~~^
      |                                                         |
      |                                                         long unsigned int
  105 |    __FILE__, __LINE__, myname, epoll_ctx->epfd,
  106 |    epoll_ctx->tid, acl_pthread_self());
      |    ~~~~~~~~~~~~~~
      |             |
      |             acl_pthread_t {aka struct __pthread *}
src/stdlib/iostuff/acl_read_wait.c:104:62: error: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  104 |   acl_msg_info("%s(%d): %s, create epoll_fd: %d, tid: %lu, %lu",
      |                                                            ~~^
      |                                                              |
      |                                                              long unsigned int
src/stdlib/iostuff/acl_read_wait.c: In function 'acl_read_epoll_wait':
src/stdlib/iostuff/acl_read_wait.c:171:17: error: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'acl_pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  171 |   acl_msg_error("%s(%d): epoll_ctl error: %s, fd: %d, "
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
......
  174 |    epoll_ctx->tid, acl_pthread_self());
      |    ~~~~~~~~~~~~~~
      |             |
      |             acl_pthread_t {aka struct __pthread *}
src/stdlib/iostuff/acl_read_wait.c:172:22: note: format string is defined here
  172 |    "epfd: %d, tid: %lu, %lu", myname, __LINE__,
      |                    ~~^
      |                      |
      |                      long unsigned int
src/stdlib/iostuff/acl_read_wait.c:171:17: error: format '%lu' expects argument of type 'long unsigned int', but argument 8 has type 'pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  171 |   acl_msg_error("%s(%d): epoll_ctl error: %s, fd: %d, "
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/stdlib/iostuff/acl_read_wait.c:172:27: note: format string is defined here
  172 |    "epfd: %d, tid: %lu, %lu", myname, __LINE__,
      |                         ~~^
      |                           |
      |                           long unsigned int
src/stdlib/iostuff/acl_read_wait.c:209:18: error: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'acl_pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  209 |    acl_msg_error("%s(%d): epoll_wait error: %s, fd: %d,"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
......
  212 |     epoll_ctx->tid, acl_pthread_self());
      |     ~~~~~~~~~~~~~~
      |              |
      |              acl_pthread_t {aka struct __pthread *}
src/stdlib/iostuff/acl_read_wait.c:210:24: note: format string is defined here
  210 |     " epfd: %d, tid: %lu, %lu", myname, __LINE__,
      |                      ~~^
      |                        |
      |                        long unsigned int
src/stdlib/iostuff/acl_read_wait.c:209:18: error: format '%lu' expects argument of type 'long unsigned int', but argument 8 has type 'pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  209 |    acl_msg_error("%s(%d): epoll_wait error: %s, fd: %d,"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/stdlib/iostuff/acl_read_wait.c:210:29: note: format string is defined here
  210 |     " epfd: %d, tid: %lu, %lu", myname, __LINE__,
      |                           ~~^
      |                             |
      |                             long unsigned int
src/stdlib/iostuff/acl_read_wait.c:243:17: error: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'acl_pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  243 |   acl_msg_error("%s(%d): epoll_ctl error: %s, fd: %d, epfd: %d,"
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  244 |    " tid: %lu, %lu", myname, __LINE__, acl_last_serror(),
  245 |    fd, epoll_ctx->epfd, epoll_ctx->tid,
      |                         ~~~~~~~~~~~~~~
      |                                  |
      |                                  acl_pthread_t {aka struct __pthread *}
src/stdlib/iostuff/acl_read_wait.c:244:13: note: format string is defined here
  244 |    " tid: %lu, %lu", myname, __LINE__, acl_last_serror(),
      |           ~~^
      |             |
      |             long unsigned int
src/stdlib/iostuff/acl_read_wait.c:243:17: error: format '%lu' expects argument of type 'long unsigned int', but argument 8 has type 'pthread_t' {aka 'struct __pthread *'} [-Werror=format=]
  243 |   acl_msg_error("%s(%d): epoll_ctl error: %s, fd: %d, epfd: %d,"
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/stdlib/iostuff/acl_read_wait.c:244:18: note: format string is defined here
  244 |    " tid: %lu, %lu", myname, __LINE__, acl_last_serror(),
      |                ~~^
      |                  |
      |                  long unsigned int
cc1: all warnings being treated as errors
make: *** [Makefile:398: debug/acl_read_wait.o] Error 1

Please let me know if acl is supported on alpine linux.

**Comment by zhengshuxin** [comment]
I need to get one alpine linux envirenment to compile acl on it before acl supports alpine linux.

**Comment by Muralikrishnapithani** [comment]
Okay.. would wait for your response till then. I have used the alpine docker image and tried to build acl libs on the container.

**Comment by Muralikrishnapithani** [comment]
Hi @zhengshuxin Any update on the support on alpine linux? please let me know

**Comment by zhengshuxin** [comment]
> Hi @zhengshuxin Any update on the support on alpine linux? please let me know

I've ever tried to install Alpine linux, but encountered some problems, I'll familiar with Alpine these days.

**Comment by zhengshuxin** [comment]
> > Hi @zhengshuxin Any update on the support on alpine linux? please let me know
> 
> I've ever tried to install Alpine linux, but encountered some problems, I'll familiar with Alpine these days.

I've ported acl project to Alpine Linux, so you can update and  test it now. You should install zlib-dev before you test the samples of acl, and libucontext  should be downloaded and installed from https://github.com/kaniini/libucontext if you want to use the acl fiber module which supporting coroutine communication.

**Comment by Muralikrishnapithani** [comment]
I need to use the acl libs for redis support. For redis support, is the acl_fiber module necessary?

**Comment by zhengshuxin** [comment]
If you just want to use acl redis, acl fiber isn't necessary.

**Comment by Muralikrishnapithani** [comment]
For the below PTHREAD error, I corrected the macro where the condition is validated. Is that okay or there would be anything will be done?

src/stdlib/acl_mylog.c:133:40: error: 'PTHREAD_MUTEX_RECURSIVE_NP' undeclared (first use in this function); did you mean 'PTHREAD_MUTEX_RECURSIVE'?
  133 |  n2 = pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE_NP);
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        PTHREAD_MUTEX_RECURSIVE
src/stdlib/acl_mylog.c:133:40: note: each undeclared identifier is reported only once for each function it appears in

**Comment by zhengshuxin** [comment]
Yes, it's ok that PTHREAD_MUTEX_RECURSIVE can be used on Alpine.
