### ISSUE TITLE
Redis List 过大时出现崩溃。

### ISSUE THREAD

**Issue by zh1an** [acl-dev/acl#262]
平台：Windows
编译器：msvc2015 with update 3
acl version: 3.5.1

当某个 List 类型的数据的 item 数量为 15311351 时，使用 lrange 接口就会发生崩溃。

**崩溃地址显示的是 redis_command.cpp 的 852 行。**

![image](https://user-images.githubusercontent.com/30436038/150047983-28ee5300-d334-4b6d-8340-7b11ab18c8f5.png)

![image](https://user-images.githubusercontent.com/30436038/150048033-2509f4c5-f2ca-4afb-b040-b22acb78c38c.png)

**Comment by zhengshuxin** [comment]
有没有用当前最新的版本测试一下呢？是否也有类似问题？

**Comment by zh1an** [comment]
@zhengshuxin  没有使用最新的测试。周一我再测试测试，如果最新版本也有该问题，我再给您回复。

**Comment by zh1an** [comment]
@zhengshuxin 我使用最新的 master 分支上代码测试了一下这个问题，仍然出现了崩溃。lrange() 函数执行了很长时间，然后突然就崩溃了。

**Comment by zh1an** [comment]
@zhengshuxin 我用你的 sample 测试了。在 [这一行](https://github.com/acl-dev/acl/blob/d7fa5eab368396d4b52ae47b9f27ba86be9b35bd/lib_acl_cpp/samples/redis/redis_list/redis_list.cpp#L427) 中修改一下代码，就必定会出现崩溃。

原代码:
```
bool ret = redis.lrange(__key, 0, 1000, &result);
```

修改之后：
```
bool ret = redis.lrange(__key, 0, -1, &result);
```

你的代码里每次只是取了 1000 个元素，我测试的时候把 list 中所有的全部取出时就会出现崩溃现象。

**Comment by zhengshuxin** [comment]
一次性地提取 15311351 条记录显示应该是提取的条数过多导致的内存不够用而崩溃了，对于大量的数据建议还是分批提取，以免造成内存OOM。
