### ISSUE TITLE
acl::string::format cause a crash

### ISSUE THREAD

**Issue by Gilbert-T** [acl-dev/acl#266]
my os: ubuntu 1804
acl version: v3.5.3-6

#include "acl_cpp/lib_acl.hpp"
int main() {
    const char* dbaddr = "127.0.0.1:3306";
    const char* dbname = "test";
    acl::string key;
    key.format("%s@%s", dbname, dbaddr);
    return 0;
}
when running, I get error msg like this: 
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

what's wrong with my program?

**Comment by zhengshuxin** [comment]
I've tested your codes that is ok. You can rebuild all the acl project and try again.
