### ISSUE TITLE
Any plan to support MongoDB?

### ISSUE THREAD

**Issue by staneychan** [acl-dev/acl#289]
请问一下， 作为分布式数据库被众多中小微企业广范使用的mongoDB,  有没有计划添加支持？

**Comment by zhengshuxin** [comment]
目前还没有计划重写或封装MongoDB的客户端驱动，因为官方提供了比较丰富的客户端库，没有太大必要再次封装或重写，但这并不防碍在acl的服务器开发中使用MongoDB，有人也使用MongoDB官方的客户端库与acl的服务器框架编写应用。
