### ISSUE TITLE
incrbyfloat 函数错误使用sizeof判断char*

### ISSUE THREAD

**Issue by openkoding** [acl-dev/acl#294]
最近公司项目需要支持`redis`，所以找到了`acl`这个库，在写测试代码时发现[incrbyfloat](https://github.com/acl-dev/acl/blob/159e6b6bb46fa3ae2999c5bf953b7d1a1fb7a014/lib_acl_cpp/src/redis/redis_string.cpp#L811)不能按预期返回数据。
我在最近修改记录中发现此函数中的`buf`由`char []`改为了`char*`, 但是后面调用`get_string`时传递字符串大小的写法并未改动，仍然是`sizeof`，这会导致获取到的和预期不一致，希望您能抽空修复下这个问题。

**Comment by zhengshuxin** [comment]
谢谢提醒，此处为手误，该问题已经修复，长度应该用 FLOAT_LEN 而不应该用 sizeof(char*)。

**Comment by zhengshuxin** [comment]
谢谢提醒，此处为手误，该问题已经修复，长度应该用 FLOAT_LEN 而不应该用 sizeof(char*)。

**Comment by openkoding** [comment]
hincrbyfloat也有同样的问题

**Comment by zhengshuxin** [comment]
是的，问题已经修复，谢谢。
