### ISSUE TITLE
keys_pattern function inside redis_key.cpp is not working correclty

### ISSUE THREAD

**Issue by tm185121** [acl-dev/acl#299]
Sub: keys_pattern function inside redis_key.cpp is not working correclty

I have a cache of type Settings at zero index.
Inside that I have 4 key, values.

==
127.0.0.1:6379[2]> select 0
OK
127.0.0.1:6379> keys *
1) "Settings_2022.12.12.19.03.15.647.json"
2) "Settings_2022.12.12.17.46.29.028.json"
3) "Settings_2022.12.14.13.55.25.880.json"
4) "Settings_2022.12.12.21.15.44.710.json"
127.0.0.1:6379> keys Settings_*
1) "Settings_2022.12.12.19.03.15.647.json"
2) "Settings_2022.12.12.17.46.29.028.json"
3) "Settings_2022.12.14.13.55.25.880.json"
4) "Settings_2022.12.12.21.15.44.710.json"
====

However , when I am trying to get the keys matching the pattern -> "Settings_*" using keys_pattern function which is inside redis_key,cpp..it is always retuning "-1".
Attached the debuggin screenshot for reference. Could you please comment.
![Redis_key issue](https://user-images.githubusercontent.com/67424577/208065218-36197a1b-d604-4392-84e2-063924910f07.JPG)

**Comment by zhengshuxin** [comment]
When some error happened, you can use redis.result_error() to get the error info.

**Comment by tm185121** [comment]
Hi, 
Thanks for your reply.
I did print that error message...and i see it says => "The operation completed successfully". 
However, the number of entries matching the key is -1.

Its seen in the screenshot attached too

Thanks
Tri

**Comment by tm185121** [comment]
Got the output using acl::redis.
Closing this issue
