### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [acl-dev/acl#3]
I would like to point out that identifiers like "[`__LIB_UTIL_INCLUDE_H__`](https://github.com/zhengshuxin/acl/blob/cc05b877a2ae04d4d9c158b2aaf453e055d7c384/lib_acl/include/lib_util.h#L1)" and "[`__ACL_SEM_INCLUDE_H__`](https://github.com/zhengshuxin/acl/blob/e2bbbac332794dab7c44ade41323f32be0d006f8/lib_acl/include/thread/acl_sem.h#L2)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by zhengshuxin** [comment]
I see, but these're C codes in lib_acl and lib_protocol of acl project. And the codes in  lib_acl_cpp of acl project are writen with C++, in which macro "#pragma once" was used.

**Comment by zhengshuxin** [comment]
Oh, I think I should delete the leading and trailing underscores in C headers.

**Comment by elfring** [comment]
Would you also like to reconsider the use of any [underscore in function and variable names](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797)?
