### ISSUE TITLE
mingw支持问题

### ISSUE THREAD

**Issue by zxppandacn** [acl-dev/acl#309]
acl_define.h中包含如下代码
#ifdef MINGW
# undef _WIN32
# undef _WIN64
#else
# include "acl_define_win32.h"
#endif
而_mingw.h文件中包含如下代码
#if !defined(_WIN32) && !defined(__CYGWIN__)
#error Only Win32 target is supported!
#endif
尝试修改acl_define.h文件会遇到找不到文件等其他问题。

**Comment by zhengshuxin** [comment]
本来Acl是支持使用 Mingw 和 Cygwin 编译的，但这个环境毕竟是一个模拟环境，一方面执行效率比较低，另一方面它们总在变化，所以后来Acl不再打算支持这两个环境，建议Windows使用者使用VC2019或相关VC版本编译使用Acl。

**Comment by zxppandacn** [comment]
谢谢您的回答。知道不支持mingw就不用费时间尝试了。
