### ISSUE TITLE
MYSQL冲突

### ISSUE THREAD

**Issue by yangzijiang98** [acl-dev/acl#315]

**Comment by yangzijiang98** [comment]
老师您好，想请问一下和mysql的冲突应该怎么解决呢
In file included from /usr/include/acl-lib/acl_cpp/lib_acl.hpp:118:0,
                 from 01_globals.h:10,
                 from 06_db.cpp:7:
/usr/include/acl-lib/acl_cpp/db/db_mysql.hpp:8:25: error: conflicting declaration ‘typedef struct st_mysql MYSQL’
 typedef struct st_mysql MYSQL;
                         ^
In file included from 06_db.cpp:4:0:
/usr/include/mysql/mysql.h:333:3: note: previous declaration as ‘typedef struct MYSQL MYSQL’
 } MYSQL;

**Comment by zhengshuxin** [comment]
可以在/usr/include/acl-lib/acl_cpp/db/db_mysql.hpp中暂将 ypedef struct st_mysql MYSQL; 这行注释掉。

**Comment by zhengshuxin** [comment]
已经将 db_mysql.hpp 中的 MYSQL 类型去掉了，应该不会有冲突了。
