### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by Zhang1n** [acl-dev/acl#328]
+ Chmod 0755 '/root/rpmbuild/BUILDROOT/acl-3.6.1-7.aarch64//usr/lib64/libacl.so.*.*.*
chmod: cannot access '/root/rpmbuild/BUILDR0OT/acl-3.6.1-7.aarch64//usr/lib64/libacl.so.*.*.*	: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.BMzfLA (%install)
RPM build errors:
Bad exit status from /var/tmp/rpm-tmp.BMzfLA (%install)

**Comment by zhengshuxin** [comment]
目前RPM的安装仅支持CentOS平台。

**Comment by Zhang1n** [comment]
没有吧 我发现低版本在openeuler平台是适合的

**Comment by zhengshuxin** [comment]
估计得要针对openseuler做适配，你可以尝试修改一下 packagine 下的打包文件。

**Comment by Zhang1n** [comment]
我这边换了一种办法编译安装： 
cd build
cmake ..   
make
make install的时候报错  没有install的这个target，makefile里面没有install 这个目标  这个是为什么

**Comment by zhengshuxin** [comment]
原来增加cmake方式编译主要是为了可以在Android Studio编译，所以没有增加 install 指令，现在增加了 install 方式，可以再试试。

**Comment by Zhang1n** [comment]
您好，感谢您，用您这种是可以编译安装的，这个安装编译后是不是需要设置一下环境变量呀，因为我在命令行执行acl，报命令没找到这个错误

**Comment by zhengshuxin** [comment]
acl只是一个开发库，没有acl命令，你可以基于acl库开发自己的服务程序。

**Comment by Zhang1n** [comment]
那如何检验我这边是安装成功了呢，有没有什么命令可以检验的

**Comment by zhengshuxin** [comment]
一般来说运行 make install 后如果返回 OK 就表示成功了；另外，你也可以手工去安装目录下查看一下安装库文件。
