### ISSUE TITLE
fiber消息队列的惊群问题

### ISSUE THREAD

**Issue by ChrisCatCP** [acl-dev/acl#333]
我看到fiber的文档里有写到fiber_tbox有多消费者惊群的问题,所以在多线程多协程环境下需要用什么办法来避免这个问题呢

**Comment by zhengshuxin** [comment]
> 我看到fiber的文档里有写到fiber_tbox有多消费者惊群的问题,所以在多线程多协程环境下需要用什么办法来避免这个问题呢

你是指哪篇文章？

**Comment by ChrisCatCP** [comment]
> > 我看到fiber的文档里有写到fiber_tbox有多消费者惊群的问题,所以在多线程多协程环境下需要用什么办法来避免这个问题呢
> 
> 你是指哪篇文章？

https://github.com/acl-dev/acl/blob/master/blog/fiber.md
这里写的

**Comment by zhengshuxin** [comment]
如果多个消费者协程在不同的线程中就可能存在惊群问题，如果多个消费者在同一个线程中则一般不会产生惊群现象。

**Comment by ChrisCatCP** [comment]
就是多个线程😣  就是看到文章里有写，但是没怎么提到有什么办法避免，只能自己指定提交到某一个线程吗

**Comment by zhengshuxin** [comment]
> 就是多个线程😣 就是看到文章里有写，但是没怎么提到有什么办法避免，只能自己指定提交到某一个线程吗

可以给每个线程创建一个 box，从各自的box里接收消息。

**Comment by ChrisCatCP** [comment]
好的，谢谢，明白了
