### ISSUE TITLE
使用redis库读取返回乱码

### ISSUE THREAD

**Issue by hechange** [acl-dev/acl#336]
使用acl::redis的类连接后调用hgetall读取hash里面存的字符串name71832í返回的是m_szName = "name71832铆"
![image](https://github.com/acl-dev/acl/assets/107619420/bc75c96c-a291-4544-8489-f89ddaf83ef3)
![image](https://github.com/acl-dev/acl/assets/107619420/d5e3787c-171e-4cae-8fc6-a0f78eb16253)
这种应该怎么解决呢

**Comment by zhengshuxin** [comment]
acl 里 redis 模块不对输入输出数据做任何特殊处理，你需要检查一下输入的数据是不是本身就已乱了。

**Comment by hechange** [comment]
> acl 里 redis 模块不对输入输出数据做任何特殊处理，你需要检查一下输入的数据是不是本身就已乱了。

![image](https://github.com/acl-dev/acl/assets/107619420/9f5cf7e4-45fa-443a-9a8e-289d93b77889)
使用rdm能正常显示，使用acl里的redis模块显示乱码

**Comment by hechange** [comment]
> acl 里 redis 模块不对输入输出数据做任何特殊处理，你需要检查一下输入的数据是不是本身就已乱了。

![image](https://github.com/acl-dev/acl/assets/107619420/ced78b13-1584-49ea-8a70-fc71941c3ef6)
在rdm里面能正常显示

**Comment by zhengshuxin** [comment]
可以使用 acl 里的 hset 命令写一下，然后再用 hgetall 类的读一下，看看是否有乱码现象。
