### ISSUE TITLE
lib_acl\src\thread\acl_pthread.c 存在截断问题

### ISSUE THREAD

**Issue by heheda123123** [acl-dev/acl#340]
使用自带xmake进行编译，报错如图，
`lib_acl\src\thread\acl_pthread.c(184)`
从 void* 转到DWORD，在64位上截断了，编译不过
![image](https://github.com/acl-dev/acl/assets/97490782/a828b4e3-d7ed-4e7f-b6b7-43b22e9890b3)

**Comment by zhengshuxin** [comment]
此问题已经修复，多谢提醒。
