### ISSUE TITLE
容器部署问题

### ISSUE THREAD

**Issue by dragon-dan** [acl-dev/acl#346]
郑老师，想请教一下现在遇到的问题
linux下用acl编译了一个静态http服务程序，版本：3.6.1-6
测试环境run_alone模式工作
（之前发现没法用nohup模式后台运行，发现可以用tmux保证运行不退出）
正式环境用的到的是k8s部署服务，看了下run_daemon模式文档，正式环境下应该没办法部署这么一套，
我的想法是，k8s集群管理各个容器的生命，每个容器里面依然使用run_alone模式运行，效果和run_daemon模式差不多。

现在开始尝试放到容器中运行，现象是无法正常运行，根据日志看没几行代码就挂了，
手动进入容器使用./myserver 启动又是正常的，感觉好像就是run_alone模式没法后台运行，
只要是前台./运行就没问题，放到后台运行就崩溃，容器运行也是崩掉。
tmux用着看起了算是个前台运行，比较正常没崩。

如果不能解决运行问题就没法上线，目前不知道是我思路不对，还是编出来的二进制程序有问题，还是run_alone模式确实不能后台运行

**Comment by zhengshuxin** [comment]
在容器里运行时，可以以run_daemon模式运行在acl_mater管理进程下；如果不想使用acl_master管理，可以修改一下 main.cpp 里入口程序，使用系统API daemon() 使程序运行在后台。

**Comment by dragon-dan** [comment]
容器镜像有限制不能在里面安装acl_master，我先试试加上 int daemon(int nochdir, int noclose)这个能不能解决

**Comment by zhengshuxin** [comment]
我平时的项目就是在容器环境里使用acl_master的，应该没有限制才对。

**Comment by dragon-dan** [comment]
基础镜像是其他方定制的，不晓得里面搞了什么，放进去报错容器起不来，很奇怪，暂时没空去找镜像的原因，跑起来能用再说

**Comment by dragon-dan** [comment]
daemon() 后台运行不行，进程直接就没了
```
    s_info("linux run daemon()");
    if (daemon(0, 0) == -1) 
    {
         s_info("daemon() error");
    }
     
     #endif

     ms.run_alone(addrs, cfg_file, count, max_threads);
```
[root@iZwz904izv5zpji57f9mp0Z act]# chmod +x actserver
[root@iZwz904izv5zpji57f9mp0Z act]# ./actserver
[2024-07-30 13:17:28.247][m_sink:I][t:3948144|main.cpp:34] init_spdlog end.
[2024-07-30 13:17:28.247][m_sink:I][t:3948144|aclmain.cpp:115] aclmain start
[2024-07-30 13:17:28.247][m_sink:I][t:3948144|aclmain.cpp:173] listen on: NULL
[2024-07-30 13:17:28.247][m_sink:I][t:3948144|aclmain.cpp:196] argc < 3
[2024-07-30 13:17:28.247][m_sink:I][t:3948144|aclmain.cpp:200] linux run daemon()
[root@iZwz904izv5zpji57f9mp0Z act]# lsof -i:8288
[root@iZwz904izv5zpji57f9mp0Z act]# lsof -i:8288
[root@iZwz904izv5zpji57f9mp0Z act]# lsof -i:8288
[root@iZwz904izv5zpji57f9mp0Z act]# lsof -i:8288

**Comment by dragon-dan** [comment]
代码删的干干净净只剩下acl http壳子和spdlog，试了好多种办法都不能后台跑起来，打到容器里面直接docker run就能跑起来，docker run -d就挂了，有没有办法能用run_daemon试试，或者能不能用acl_proctl_deamon_init, acl_proctl_daemon_loop再搞一个进程做父进程来调用子进程run_alone

**Comment by dragon-dan** [comment]
[root@va-centos7 linux64]# ./master_ctl -s /home/acl-build-linux/dist/master/var/public/master.sock -a list
status  service                                         type    proc    owner   conf
200     |8288                                           4       0               /home/acl-build-linux/dist/master/conf/service/actserver.cf

servers count: 1
[root@va-centos7 linux64]# lsof -i:8288
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
acl_maste 16911 root   16u  IPv4 142655      0t0  TCP localhost:8288 (LISTEN)
acl_maste 16911 root   17u  IPv4 142656      0t0  TCP va-centos7:8288 (LISTEN)
acl_maste 16911 root   18u  IPv4 142657      0t0  TCP va-centos7:8288 (LISTEN)
acl_maste 16911 root   19u  IPv6 142658      0t0  TCP localhost:8288 (LISTEN)
acl_maste 16911 root   20u  IPv6 142661      0t0  TCP va-centos7:8288 (LISTEN)
acl_maste 16911 root   21u  IPv6 142665      0t0  TCP va-centos7:8288 (LISTEN)
[root@va-centos7 linux64]# curl localhost:8288

用acl_master后台运行，端口倒是占用了，服务访问不了，一直转圈圈

**Comment by dragon-dan** [comment]
搞了好几天，丢掉自己全部代码，重新用wizard生成httpd，终于用run_daemon跑起来了，一步一步对比调试
总结如下：
1）run_alone 模式确实不支持后台运行，nohup ./actserver 1>out.log 2>&1 & 直接崩溃，docker运行-d也是直接崩溃
2）run_daemon模式用acl_master管理，配置文件中有三个重要的东西
		#	进程日志记录文件
		master_log = *****
		#	记录进程PID的位置(对于多进程实例来说没有意义)
		ioctl_pid_dir = *****
		#	进程运行时所在的路径
		ioctl_queue_dir = *****
	这三个配置必须保证文件夹存在，否则运行就崩溃，dist/master/sh目录下不停的在生成Core文件

感觉这三个配置的说明是不是可以写到文档里面。
郑老师，后续版本能不能开放下run_alone模式支持后台运行呢

**Comment by zhengshuxin** [comment]
好的，可以考虑run_alone模式运行在后台。

**Comment by dragon-dan** [comment]
现在改造了容器，基于apline强行在里面塞了acl_master、master_ctl及自己的服务，程序是run_daemon起来了，但是好像所有进程全是后台运行的，容器起来之后估计是判断主进程没事干就退出了，整了个sh脚本里面写了个死循环卡住让容器不退出就可以了，您在容器里跑acl_master也是这么干的吗

**Comment by zhengshuxin** [comment]
acl_master 是在前台运行的。

**Comment by dragon-dan** [comment]
那就奇怪了，我在容器中用 start.sh 启动的 acl_master ，是正常工作，不加死循环容器run起来就Exit了，加上死循环卡卡住容器就不会退出，看起来效果 acl_master 就像是在后台运行

**Comment by zhengshuxin** [comment]
可以打成rpm包，安装后会放置自启动文件 /etc/init.d/acl-master

**Comment by dragon-dan** [comment]
回头试一试这个方法
