### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by ghost** [acl-dev/acl#347]
```
CMake Error at lib_fiber/c/CMakeLists.txt:101 (message):
  unknown CMAKE_SYSTEM_NAME=FreeBSD
```

**Comment by zhengshuxin** [comment]
Acl can be used on FreeBSD before, but I have no FreeBSD env now, so you can try to build Acl by running make command on FreeBSD.

**Comment by ghost** [comment]
> Acl can be used on FreeBSD before, but I have no FreeBSD env now, so you can try to build Acl by running make command on FreeBSD.

CMake fails to generate build script, how can I run gmake?

p/s: There is a Makefile in the project's root. But running gmake will only give a bunch of errors.

**Comment by ghost** [comment]
I inserted the missing `elseif(CMAKE_SYSTEM_NAME MATCHES "FreeBSD")` line after line 97:

https://github.com/acl-dev/acl/blob/ebeb2e02cbdacd76d9a241544a8504dc21cb51f2/lib_fiber/c/CMakeLists.txt#L97

But it still not work. The same error message as before, but at a different line:

```
CMake Error at lib_fiber/c/CMakeLists.txt:90 (message):
  unknown CMAKE_SYSTEM_NAME=FreeBSD
```

It seems for some reasons, `CMAKE_SYSTEM_NAME MATCHES "FreeBSD` doesn't work as expected. The result is it will always report FreeBSD as unknown.

**Comment by zhengshuxin** [comment]
Can you provide a FreeBSD env for me to build Acl ? I think it maybe easy to build and use Acl on it.

**Comment by ghost** [comment]
> Can you provide a FreeBSD env for me to build Acl ? I think it maybe easy to build and use Acl on it.

I can't help with that. The current machine I'm using only has 4GB of RAM. If you want me to setup a FreeBSD VirtualBox image and send it to you then I can't.

**Comment by zhengshuxin** [comment]
Acl can be built on FreeBSD now. You can try to build and test acl on FreeBSD.
-- zsx.
