### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [acl-dev/acl#4]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8) like the following.
- [http_pipe](https://github.com/zhengshuxin/acl/blob/79e18cc2e9cc93f646c6427742236b5b302c630b/lib_acl_cpp/src/http/http_pipe.cpp#L15)
- [master_service::thread_on_close](https://github.com/zhengshuxin/acl/blob/d381b0117dc2bf447bb80c3dcc0276f0ac0f5b50/lib_acl_cpp/samples/https_server/master_service.cpp#L99)
- [mime_body::save_body](https://github.com/zhengshuxin/acl/blob/79e18cc2e9cc93f646c6427742236b5b302c630b/lib_acl_cpp/src/mime/mime_body.cpp#L11)
- [mime_head::reset](https://github.com/zhengshuxin/acl/blob/79e18cc2e9cc93f646c6427742236b5b302c630b/lib_acl_cpp/src/mime/mime_head.cpp#L35)

**Comment by zhengshuxin** [comment]
Thanks for your suggest. It's the first time for me to learn about it, thanks again and I'll delete the useless null check in the acl codes.

**Comment by elfring** [comment]
How do you think about to delete also unnecessary checks before function calls like the following?
- [http_hdr_req_free](https://github.com/zhengshuxin/acl/blob/8fe7a1c4ac59e57849f62a0d7815b0f4e236c91d/lib_protocol/src/http/http_hdr_req.c#L292)
- [acl_array_destroy](https://github.com/zhengshuxin/acl/blob/cc05b877a2ae04d4d9c158b2aaf453e055d7c384/lib_acl/include/stdlib/acl_array.h#L57)
- [acl_json_free_array](https://github.com/zhengshuxin/acl/blob/3c856acfd3d12c0dcb50588196d95a28e0fa7074/lib_acl/src/json/acl_json_util.c#L16)
- [acl_myfree](https://github.com/zhengshuxin/acl/blob/cc05b877a2ae04d4d9c158b2aaf453e055d7c384/lib_acl/include/stdlib/acl_mymalloc.h#L68)
