### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [acl-dev/acl#6]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html) ⇒ [locker::init_mutex](https://github.com/zhengshuxin/acl/blob/79e18cc2e9cc93f646c6427742236b5b302c630b/lib_acl_cpp/independent/connpool/src/locker.cpp#L19)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html) ⇒ [ioctl_init](https://github.com/zhengshuxin/acl/blob/79e18cc2e9cc93f646c6427742236b5b302c630b/lib_acl/src/master/template/acl_ioctl_server.c#L150)

**Comment by zhengshuxin** [comment]
Yes, I'll add error check and handle for these code. Thanks

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?
