### ISSUE TITLE
Windows10 Visual Studio 2017下编译出错

### ISSUE THREAD

**Issue by myaccountl** [acl-dev/acl#61]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“lib_acl_vc2012d.lib”	mime_qp	E:\迅雷下载\acl-master\lib_acl_cpp\samples\mime\mime_qp\LINK	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“lib_acl_d.lib”	HttpClient	E:\迅雷下载\acl-master\lib_acl_cpp\samples\HttpClient\LINK	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“lib_acl_cpp_d.lib”	win_dbservice	E:\迅雷下载\acl-master\lib_acl_cpp\samples\win_dbservice\LINK	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“lib_acl_d.lib”	winaio	E:\迅雷下载\acl-master\lib_acl_cpp\samples\winaio\LINK	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“polarssl.lib”	ssl_client	E:\迅雷下载\acl-master\lib_acl_cpp\samples\ssl\ssl_client\LINK	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C3848	具有类型“const server_ttl_comp”的表达式会丢失一些 const-volatile 限定符以调用“bool server_ttl_comp::operator ()(const server_ttl *,const server_ttl *)”	dispatch_manager	d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include\xutility	946	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1189	#error:  MFC does not support WINVER less than 0x0501.  Please change the definition of WINVER in your project properties or precompiled header.	winaio_vc2012	d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\include\afxv_w32.h	40

**Comment by zhengshuxin** [comment]
请用VC2008, 2010, 2012, 2013或 2015 打开工程文件：acl_cpp_vc20xxx.sln，至于 2017 工程你可以参考其它版本的工程文件 修改。
