### ISSUE TITLE
redis_list::lpop & rpop返回值与头文件中的注释不符

### ISSUE THREAD

**Issue by liuaifu** [acl-dev/acl#93]
acl::redis_list command;
	redis.set_cluster(command);

	int n = command.rpush("test_list", "value1", "value2", NULL);
	EXPECT_EQ(n, 2);

	acl::string str;
	n = command.lpop("test_list", str);
	EXPECT_EQ(n, 1);
	EXPECT_EQ(str, "value1");

command.lpop返回值期望1，实际6。

**Comment by zhengshuxin** [comment]
是注释有误，已修复

**Comment by liuaifu** [comment]
rpop还没改呢。
